import { EPF_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const epfClaimFileSubmissionFormDefinition: DataCollectionForm = {
  id: "epf-claim-file-submission",
  nameSi: "සේවක අර්ථසාධක අරමුදල් ප්‍රතිලාභ ගොනු භාරදීම",
  nameEn: "EPF Benefit Claim File Submission Authorization",
  documentPath: "/forms/epf/claim-file-submission.pdf",
  category: EPF_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds to one or more {{fieldKey}} placeholders in the Firebase OCR/layout annotation template.",
    "When applying generated values, replace only matching placeholders. Do not modify fixed OCR text, bounding boxes, labels, reading order, page number, or other layout metadata.",
    "Generate one internally consistent synthetic EPF member, authorized representative, bank account, and embassy-certification scenario.",
    "senderAddress and memberPermanentAddress should normally describe the same member residential address.",
    "The form pre-prints the request year as 2021. Therefore requestDate must be a valid date in 2021 and only its month/day components should be rendered into the printed date blanks.",
    "memberName, bankAccountHolderName, and embassyCertifiedMemberName must refer to the same synthetic EPF member and should normally contain exactly the same name.",
    "memberNicOrPassportNumber must contain a plausible synthetic Sri Lankan NIC number or a plausible valid passport number. For consistency with the embassy-certification paragraph, prefer a synthetic passport number and use the same value for embassyPassportNumber.",
    "memberNumber must be a plausible synthetic EPF membership number.",
    "authorizedPersonName must be a plausible synthetic Sri Lankan name and must not refer to a real public figure.",
    "authorizedPersonNicNumber must be a plausible synthetic Sri Lankan NIC number and must be different from the member's identifier.",
    "relationshipToMember must be a realistic relationship such as spouse, son, daughter, sibling, or other close relative/authorized person.",
    "bankAccountHolderName must be the EPF member name.",
    "bankAccountNumber, bankName, and bankBranch must describe one plausible synthetic Sri Lankan bank account.",
    "memberEmail must be a synthetic email address and memberPhone must be a plausible synthetic Sri Lankan telephone number.",
    "embassyPassportNumber must match the member's passport number used in memberNicOrPassportNumber when a passport number is used there.",
    "embassyCertifiedMemberName must exactly match memberName.",
    "embassyOfficerName and embassyOfficerDesignation must be synthetic and must not identify a real embassy official.",
    "Keep generated values concise enough to fit naturally within their assigned bounding boxes.",
    "Use only synthetic personal, banking, membership, contact, and document identifiers. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys defined in the fields array. Do not invent additional ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, or layout information. Those are already stored in the Firebase annotation template.",
    "Member signature, left/right fingerprints, embassy-officer signature, and embassy official stamp are represented separately as image-style annotation regions and should not be returned as ordinary text values unless the rendering pipeline explicitly supports synthetic image assets."
  ],

  fields: [
    {
      key: "senderAddress",
      labelSi: "ලිපිය යවන සාමාජිකයාගේ ලිපිනය",
      labelEn: "Sender / Member Address",
      type: "address",
      required: true,
    },
    {
      key: "requestDate",
      labelSi: "ඉල්ලීමේ දිනය",
      labelEn: "Request Date",
      type: "date",
      required: true,
      helpTextSi: "2021 වර්ෂයට අදාළ YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "memberName",
      labelSi: "සාමාජික නම",
      labelEn: "Member Name",
      type: "text",
      required: true,
    },
    {
      key: "memberNicOrPassportNumber",
      labelSi: "ජාතික හැඳුනුම්පත් අංකය / වලංගු විදේශ ගමන් බලපත්‍ර අංකය",
      labelEn: "NIC Number / Valid Foreign Passport Number",
      type: "text",
      required: true,
    },
    {
      key: "memberNumber",
      labelSi: "සාමාජික අංකය",
      labelEn: "Member Number",
      type: "text",
      required: true,
    },
    {
      key: "memberPermanentAddress",
      labelSi: "සාමාජිකයාගේ ස්ථිර පදිංචි ලිපිනය",
      labelEn: "Permanent Residential Address of Member",
      type: "address",
      required: true,
    },
    {
      key: "authorizedPersonName",
      labelSi: "ගොනුව භාරදීමට බලය පවරන අයගේ නම",
      labelEn: "Name of Authorized Person",
      type: "text",
      required: true,
    },
    {
      key: "authorizedPersonNicNumber",
      labelSi: "බලය පවරන අයගේ ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "NIC Number of Authorized Person",
      type: "nic",
      required: true,
    },
    {
      key: "relationshipToMember",
      labelSi: "සාමාජිකයාට ඇති ඥාතිත්වය / සම්බන්ධතාවය",
      labelEn: "Relationship to Member",
      type: "text",
      required: true,
    },
    {
      key: "bankAccountHolderName",
      labelSi: "බැංකු ගිණුමේ සාමාජික නම",
      labelEn: "Member Name for Bank Account",
      type: "text",
      required: true,
    },
    {
      key: "bankAccountNumber",
      labelSi: "ගිණුම් අංකය",
      labelEn: "Bank Account Number",
      type: "text",
      required: true,
    },
    {
      key: "bankName",
      labelSi: "බැංකුවේ නම",
      labelEn: "Bank Name",
      type: "text",
      required: true,
    },
    {
      key: "bankBranch",
      labelSi: "බැංකු ශාඛාව",
      labelEn: "Bank Branch",
      type: "text",
      required: true,
    },
    {
      key: "memberEmail",
      labelSi: "විද්‍යුත් ලිපිනය",
      labelEn: "Email Address",
      type: "text",
      required: true,
    },
    {
      key: "memberPhone",
      labelSi: "දුරකථන අංකය",
      labelEn: "Telephone Number",
      type: "phone",
      required: true,
    },
    {
      key: "embassyPassportNumber",
      labelSi: "තානාපති කාර්යාලය විසින් තහවුරු කරන විදේශ ගමන් බලපත්‍ර අංකය",
      labelEn: "Passport Number Certified by Embassy",
      type: "text",
      required: true,
    },
    {
      key: "embassyCertifiedMemberName",
      labelSi: "තානාපති කාර්යාලය විසින් තහවුරු කරන සාමාජිකයාගේ නම",
      labelEn: "Member Name Certified by Embassy",
      type: "text",
      required: true,
    },
    {
      key: "embassyOfficerName",
      labelSi: "තානාපති කාර්යාල නිලධාරියාගේ නම",
      labelEn: "Embassy Officer Name",
      type: "text",
      required: true,
    },
    {
      key: "embassyOfficerDesignation",
      labelSi: "තානාපති කාර්යාල නිලධාරියාගේ තනතුර",
      labelEn: "Embassy Officer Designation",
      type: "text",
      required: true,
    },
  ],
};
