import { EPF_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const epfKFormDefinition: DataCollectionForm = {
  id: "k-form",
  nameSi: "කේ පෝරමය",
  nameEn: "K Form",
  documentPath: "/forms/epf/k-form.pdf",
  category: EPF_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated value corresponds to a {fieldKey} placeholder in the static EPF K Form OCR/layout annotation template.",
    "Replace only the matching placeholder value. Do not modify printed OCR text, page number, bounding box, annotation label, reading order, or other layout metadata.",
    "Generate realistic synthetic values appropriate for a Sri Lankan Employees' Provident Fund claim form.",
    "Keep the member's names, NIC information, age/date of birth, employment dates, employer details, membership numbers, and bank details internally consistent.",
    "The date employment ceased must be later than the member's plausible employment start period and compatible with the member's age.",
    "Previous-employer records are optional; when generated, keep their leaving dates earlier than the last-employer leaving date.",
    "Keep the four name-certificate values consistent. Minor formatting differences are allowed only where realistic; they must still clearly refer to the same synthetic person.",
    "If bank-account details are generated, account type, bank name, branch, and account number must be mutually consistent.",
    "Use synthetic NIC, EPF/membership, bank, employer, and contact-like identifiers. Do not use real public figures or knowingly real personal identifiers.",
    "For yes/no fields such as nicCopyAnnexed, return a concise value such as ඔව් or නැත.",
    "Keep generated text concise enough to fit naturally within the bounding box assigned to its placeholder.",
    "Do not return OCR text, bounding boxes, labels, page numbers, or reading order. Those are already stored in the static annotation template.",
    "Signature, thumb-mark, and similar image regions are stored separately in the annotation template and should not be returned as ordinary text values unless your rendering pipeline explicitly supports synthetic image assets.",
  ],

  fields: [
    {
      key: "memberFullName",
      labelSi: "සේවකයාගේ / සාමාජිකයාගේ සම්පූර්ණ නම",
      labelEn: "Full name of member",
      type: "text",
      required: true,
    },
    {
      key: "memberAddress",
      labelSi: "සාමාජිකයාගේ ලිපිනය",
      labelEn: "Address of member",
      type: "address",
      required: true,
    },
    {
      key: "fatherFullName",
      labelSi: "සාමාජිකයාගේ පියාගේ සම්පූර්ණ නම",
      labelEn: "Full name of member's father",
      type: "text",
      required: true,
    },
    {
      key: "motherFullName",
      labelSi: "සාමාජිකයාගේ මවගේ සම්පූර්ණ නම",
      labelEn: "Full name of member's mother",
      type: "text",
      required: true,
    },
    {
      key: "spouseFullName",
      labelSi: "සාමාජිකයාගේ කලත්‍රයාගේ සම්පූර්ණ නම",
      labelEn: "Full name of member's spouse (if married)",
      type: "text",
      required: false,
    },
    {
      key: "distinguishingMarks",
      labelSi: "හඳුනාගැනීමේ ස්වභාවික විශේෂ ලකුණු",
      labelEn: "Natural distinguishing marks of member",
      type: "text",
      required: false,
    },
    {
      key: "lastEmployerNumber",
      labelSi: "අවසාන සේවායෝජකයාගේ අංකය",
      labelEn: "Last employer number",
      type: "text",
      required: true,
    },
    {
      key: "lastEmployerLetter",
      labelSi: "අවසාන සේවායෝජකයාගේ අකුර",
      labelEn: "Last employer letter",
      type: "text",
      required: false,
    },
    {
      key: "lastEmployerMembershipNumber",
      labelSi: "අවසාන සේවායෝජකයා යටතේ සාමාජිකත්ව අංකය",
      labelEn: "Membership number under last employer",
      type: "text",
      required: true,
    },
    {
      key: "lastEmployerLeavingDate",
      labelSi: "අවසාන සේවායෝජකයාගෙන් ඉවත්වූ දිනය",
      labelEn: "Leaving date from last employer",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "previousEmployer1Number",
      labelSi: "පෙර සේවායෝජක 1 අංකය",
      labelEn: "Previous employer 1 number",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer1Letter",
      labelSi: "පෙර සේවායෝජක 1 අකුර",
      labelEn: "Previous employer 1 letter",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer1MembershipNumber",
      labelSi: "පෙර සේවායෝජක 1 සාමාජිකත්ව අංකය",
      labelEn: "Previous employer 1 membership number",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer1LeavingDate",
      labelSi: "පෙර සේවායෝජක 1 ඉවත්වූ දිනය",
      labelEn: "Previous employer 1 leaving date",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "previousEmployer2Number",
      labelSi: "පෙර සේවායෝජක 2 අංකය",
      labelEn: "Previous employer 2 number",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer2Letter",
      labelSi: "පෙර සේවායෝජක 2 අකුර",
      labelEn: "Previous employer 2 letter",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer2MembershipNumber",
      labelSi: "පෙර සේවායෝජක 2 සාමාජිකත්ව අංකය",
      labelEn: "Previous employer 2 membership number",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer2LeavingDate",
      labelSi: "පෙර සේවායෝජක 2 ඉවත්වූ දිනය",
      labelEn: "Previous employer 2 leaving date",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "previousEmployer3Number",
      labelSi: "පෙර සේවායෝජක 3 අංකය",
      labelEn: "Previous employer 3 number",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer3Letter",
      labelSi: "පෙර සේවායෝජක 3 අකුර",
      labelEn: "Previous employer 3 letter",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer3MembershipNumber",
      labelSi: "පෙර සේවායෝජක 3 සාමාජිකත්ව අංකය",
      labelEn: "Previous employer 3 membership number",
      type: "text",
      required: false,
    },
    {
      key: "previousEmployer3LeavingDate",
      labelSi: "පෙර සේවායෝජක 3 ඉවත්වූ දිනය",
      labelEn: "Previous employer 3 leaving date",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "ageAndDateOfBirth",
      labelSi: "සාමාජිකයාගේ වයස සහ උපන්දිනය",
      labelEn: "Age and date of birth of member",
      type: "text",
      required: true,
    },
    {
      key: "dateEmploymentCeased",
      labelSi: "අවසාන සේවායෝජකයා යටතේ සේවය නතර කළ දිනය",
      labelEn: "Date employment ceased under last employer",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "causeOfCessation",
      labelSi: "සේවය නතර කිරීමට හේතුව",
      labelEn: "Cause of cessation of employment",
      type: "text",
      required: true,
    },
    {
      key: "lastEmployerNameAddress",
      labelSi: "අවසාන සේවායෝජකයාගේ නම සහ ලිපිනය",
      labelEn: "Name and address of the last employer",
      type: "address",
      required: true,
    },
    {
      key: "nameOnNic",
      labelSi: "ජාතික හැඳුනුම්පතේ සඳහන් නම",
      labelEn: "Name appearing on National Identity Card",
      type: "text",
      required: true,
    },
    {
      key: "nicNumber",
      labelSi: "ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "Identity Card No.",
      type: "nic",
      required: true,
    },
    {
      key: "nicIssueDate",
      labelSi: "ජාතික හැඳුනුම්පත නිකුත් කළ දිනය",
      labelEn: "Date of Issue",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "nicCopyAnnexed",
      labelSi: "හැඳුනුම්පත් පිටපත අමුණා තිබේද",
      labelEn: "NIC copy annexed",
      type: "text",
      required: true,
    },
    {
      key: "bankAccountType",
      labelSi: "බැංකු ගිණුම් වර්ගය",
      labelEn: "Type of account",
      type: "text",
      required: false,
    },
    {
      key: "bankName",
      labelSi: "බැංකුවේ නම",
      labelEn: "Name of Bank",
      type: "text",
      required: false,
    },
    {
      key: "bankAccountNumber",
      labelSi: "බැංකු ගිණුම් අංකය",
      labelEn: "Account No.",
      type: "text",
      required: false,
    },
    {
      key: "bankBranch",
      labelSi: "බැංකු ශාඛාව",
      labelEn: "Bank Branch",
      type: "text",
      required: false,
    },
    {
      key: "bankDeclarationDate",
      labelSi: "බැංකු ප්‍රකාශ දිනය",
      labelEn: "Date for bank-account declaration",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "birthMarriageCertificateName",
      labelSi: "උප්පැන්න / විවාහ සහතිකයේ නම",
      labelEn: "Name in Birth Certificate / Marriage Certificate",
      type: "text",
      required: true,
    },
    {
      key: "nicCertifiedName",
      labelSi: "ජාතික හැඳුනුම්පතේ නම",
      labelEn: "Name in National Identity Card",
      type: "text",
      required: true,
    },
    {
      key: "membershipCardName",
      labelSi: "B සාමාජිකත්ව කාඩ්පතේ නම",
      labelEn: "Name in B Card (Membership Card)",
      type: "text",
      required: true,
    },
    {
      key: "epfAccountName",
      labelSi: "ශ්‍රී ලංකා මහ බැංකුවේ EPF ගිණුමේ නම",
      labelEn: "Name in EPF Account at Central Bank of Sri Lanka",
      type: "text",
      required: true,
    },
    {
      key: "witnessNameDesignationAddress",
      labelSi: "සාක්ෂිකරුගේ නම, තනතුර සහ ලිපිනය",
      labelEn: "Name, designation and address of witness",
      type: "address",
      required: false,
    },
    {
      key: "employerCertifierName",
      labelSi: "සේවායෝජක සහතිකකරුගේ නම",
      labelEn: "Employer certifier name",
      type: "text",
      required: true,
    },
    {
      key: "employerRole",
      labelSi: "සේවායෝජක සහතිකකරුගේ භූමිකාව",
      labelEn: "Manager / Superintendent / Proprietor",
      type: "text",
      required: true,
    },
    {
      key: "employerEstablishmentName",
      labelSi: "ආයතනයේ නම",
      labelEn: "Establishment name",
      type: "text",
      required: true,
    },
    {
      key: "employerEstablishmentLocation",
      labelSi: "ආයතනය පිහිටි ස්ථානය",
      labelEn: "Establishment location",
      type: "address",
      required: true,
    },
    {
      key: "certifiedMemberName",
      labelSi: "සහතික කරන සාමාජිකයාගේ නම",
      labelEn: "Certified member name",
      type: "text",
      required: true,
    },
    {
      key: "certifiedMembershipNumber",
      labelSi: "සහතික කරන සාමාජිකත්ව අංකය",
      labelEn: "Certified membership number",
      type: "text",
      required: true,
    },
    {
      key: "employmentLocation",
      labelSi: "සේවය කළ ආයතනය / ස්ථානය",
      labelEn: "Employment location",
      type: "text",
      required: true,
    },
    {
      key: "contributionMonth",
      labelSi: "අවසාන දායකත්ව මාසය",
      labelEn: "Last contribution month",
      type: "text",
      required: true,
    },
    {
      key: "contributionYear",
      labelSi: "අවසාන දායකත්ව වර්ෂය",
      labelEn: "Last contribution year",
      type: "number",
      required: true,
    },
    {
      key: "employerNumber",
      labelSi: "සේවායෝජකයාගේ අංකය",
      labelEn: "Employer's number",
      type: "text",
      required: true,
    },
    {
      key: "employerCertificationDate",
      labelSi: "සේවායෝජක සහතික දිනය",
      labelEn: "Employer certification date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "employerRegistrationNumber",
      labelSi: "සේවායෝජක ලියාපදිංචි අංකය",
      labelEn: "Employer's Registration Number",
      type: "text",
      required: false,
    },
    {
      key: "employmentNumber",
      labelSi: "රැකියා අංකය",
      labelEn: "Employment Number",
      type: "text",
      required: false,
    },
    {
      key: "annexDContributionTable",
      labelSi: "D ඇමුණුමේ දායක මුදල් විස්තර",
      labelEn: "Annex D contribution details",
      type: "text",
      required: false,
    },
    {
      key: "annexEmployerName",
      labelSi: "D ඇමුණුමේ සේවායෝජක නම",
      labelEn: "Employer name in Annex D",
      type: "text",
      required: false,
    },
    {
      key: "annexDate",
      labelSi: "D ඇමුණුමේ දිනය",
      labelEn: "Annex D date",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    }
  ],
};
