import { EPF_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const epfLetterOfIndemnityFormDefinition: DataCollectionForm = {
  id: "epf-letter-of-indemnity",
  nameSi: "හානි පූරණ ලිපිය",
  nameEn: "Letter of Indemnity",
  documentPath: "/forms/epf/letter-of-indemnity.pdf",
  category: EPF_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds to one or more {{fieldKey}} placeholders in the Firebase OCR/layout annotation template.",
    "Page 1 is the Sinhala version and page 2 is the English version of the same declaration. The same generated value must therefore be reused for every occurrence of the same fieldKey across both pages.",
    "When applying generated values, replace only matching placeholders. Do not modify fixed OCR text, bounding boxes, labels, reading order, page numbers, headings, footnotes, or other layout metadata.",
    "Generate one internally consistent synthetic EPF-member and former-employment scenario.",
    "memberFullName, memberAddress, memberNicNumber, occupation, institutionNameAndAddress, employmentStartDate, employmentEndDate, epfMembershipNumber, nameInCbsl, and employerName must all describe the same member and former employer history.",
    "memberFullName must be a plausible synthetic Sri Lankan name and must not refer to a real public figure.",
    "memberNicNumber must be a plausible synthetic Sri Lankan National Identity Card number.",
    "memberAddress must be a plausible synthetic Sri Lankan residential address.",
    "occupation must be a realistic occupation for the stated institution.",
    "institutionNameAndAddress must identify a plausible synthetic former employer/institution that is no longer in operation and whose employer is not known or traceable, as stated by the fixed declaration text.",
    "employerName must correspond to the employer/institution named in institutionNameAndAddress.",
    "employmentStartDate and employmentEndDate must use YYYY-MM-DD, and employmentStartDate must be earlier than employmentEndDate.",
    "epfMembershipNumber must be a plausible synthetic EPF membership number and must be reused everywhere the form refers to the membership number.",
    "nameInCbsl must be a plausible version of the member's name as recorded at the Central Bank of Sri Lanka and must still clearly refer to the same person as memberFullName.",
    "signedDate must use YYYY-MM-DD. The annotation renderer must split it into the year/month/day blanks on the Sinhala page and into day/month/year wording on the English page.",
    "For the English phrase 'Two Thousand ...', render only the year portion after 'Two Thousand'. For example, a 2026 signedDate should render 'Twenty Six' in that blank.",
    "signedPlace must be a plausible Sri Lankan place where the Sinhala declaration was signed.",
    "Generate two plausible synthetic witnesses. Each witness name, NIC number, and address must describe the same witness and must not refer to a real public figure.",
    "witness1NicNumber and witness2NicNumber must be plausible synthetic Sri Lankan NIC numbers and must be different from each other and from memberNicNumber.",
    "Keep all generated values concise enough to fit naturally within the corresponding dotted-line bounding boxes.",
    "Use only synthetic personal, employment, membership, and address information. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys defined in the fields array. Do not invent additional ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, or layout information. Those are already stored in the Firebase annotation template.",
    "The member signature and both witness signatures are represented separately as Signature regions in the annotation template and should not be returned as ordinary text values unless the rendering pipeline explicitly supports synthetic signature-image assets."
  ],

  fields: [
    {
      key: "memberFullName",
      labelSi: "සාමාජිකයාගේ සම්පූර්ණ නම",
      labelEn: "Full Name",
      type: "text",
      required: true,
    },
    {
      key: "memberAddress",
      labelSi: "සාමාජිකයාගේ ලිපිනය",
      labelEn: "Address",
      type: "address",
      required: true,
    },
    {
      key: "memberNicNumber",
      labelSi: "සාමාජිකයාගේ ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "National Identity Card Number",
      type: "nic",
      required: true,
    },
    {
      key: "occupation",
      labelSi: "රැකියාව",
      labelEn: "Occupation",
      type: "text",
      required: true,
    },
    {
      key: "institutionNameAndAddress",
      labelSi: "සේවය කළ ආයතනයේ නම සහ ලිපිනය",
      labelEn: "Name and Address of the Institution",
      type: "address",
      required: true,
    },
    {
      key: "employmentStartDate",
      labelSi: "සේවය ආරම්භ කළ දිනය",
      labelEn: "Employment Start Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "employmentEndDate",
      labelSi: "සේවය අවසන් කළ දිනය",
      labelEn: "Employment End Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "epfMembershipNumber",
      labelSi: "සේවක අර්ථසාධක අරමුදල් සාමාජික අංකය",
      labelEn: "EPF Membership Number",
      type: "text",
      required: true,
    },
    {
      key: "nameInCbsl",
      labelSi: "ශ්‍රී ලංකා මහ බැංකු වාර්තාවේ සඳහන් නම",
      labelEn: "Name in CBSL",
      type: "text",
      required: true,
    },
    {
      key: "employerName",
      labelSi: "සේවායෝජකයාගේ / ආයතනයේ නම",
      labelEn: "Employer Name",
      type: "text",
      required: true,
    },
    {
      key: "signedDate",
      labelSi: "අත්සන් කළ දිනය",
      labelEn: "Date Signed",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "signedPlace",
      labelSi: "අත්සන් කළ ස්ථානය",
      labelEn: "Place Signed",
      type: "text",
      required: true,
    },
    {
      key: "witness1Name",
      labelSi: "පළමු සාක්ෂිකරුගේ නම",
      labelEn: "Witness 1 Name",
      type: "text",
      required: true,
    },
    {
      key: "witness1NicNumber",
      labelSi: "පළමු සාක්ෂිකරුගේ ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "Witness 1 NIC Number",
      type: "nic",
      required: true,
    },
    {
      key: "witness1Address",
      labelSi: "පළමු සාක්ෂිකරුගේ ලිපිනය",
      labelEn: "Witness 1 Address",
      type: "address",
      required: true,
    },
    {
      key: "witness2Name",
      labelSi: "දෙවන සාක්ෂිකරුගේ නම",
      labelEn: "Witness 2 Name",
      type: "text",
      required: true,
    },
    {
      key: "witness2NicNumber",
      labelSi: "දෙවන සාක්ෂිකරුගේ ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "Witness 2 NIC Number",
      type: "nic",
      required: true,
    },
    {
      key: "witness2Address",
      labelSi: "දෙවන සාක්ෂිකරුගේ ලිපිනය",
      labelEn: "Witness 2 Address",
      type: "address",
      required: true,
    },
  ],
};
