import { EPF_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const epfMemberVerificationFormDefinition: DataCollectionForm = {
  id: "epf-member-verification",
  nameSi: "සේවක අර්ථ සාධක අරමුදල ප්‍රතිලාභ ගෙවීම - සාමාජික තහවුරු කිරීම",
  nameEn: "EPF Benefit Payment - Member Verification",
  documentPath: "/forms/epf/member-verification.pdf",
  category: EPF_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds to one or more {{fieldKey}} placeholders in the static OCR/layout annotation template.",
    "Page 1 is the Sinhala version and page 2 is the corresponding Tamil version. Reuse exactly the same generated value for every occurrence of the same fieldKey across both pages.",
    "When applying generated values, replace only matching placeholders. Do not modify fixed OCR text, bounding boxes, labels, reading order, page numbers, headings, tables, footnotes, or other layout metadata.",
    "Generate one internally consistent synthetic EPF member record.",
    "memberName must be a plausible synthetic Sri Lankan name and must not refer to a real public figure.",
    "memberNumber must be a plausible synthetic EPF membership number and must be reused everywhere the form repeats the member number.",
    "memberAddress must be a plausible synthetic Sri Lankan residential address.",
    "memberAge and dateOfBirth must be mutually consistent. dateOfBirth must use YYYY-MM-DD.",
    "maritalStatus must be either විවාහක or අවිවාහක and must be consistent with spouseName.",
    "If maritalStatus is අවිවාහක, spouseName must be an empty string so the spouse-name line remains blank.",
    "If maritalStatus is විවාහක, spouseName must contain a plausible synthetic spouse name.",
    "nationalIdentityCardNumber must be a plausible synthetic Sri Lankan NIC number.",
    "fatherName and fatherDateOfBirth must describe the member's father. fatherDateOfBirth must use YYYY-MM-DD.",
    "motherName and motherDateOfBirth must describe the member's mother. motherDateOfBirth must use YYYY-MM-DD.",
    "employerOrEstateName must be a plausible synthetic Sri Lankan employer, institution, or estate where the member worked.",
    "occupationStatus must describe a realistic occupation, job grade, or employment status for the stated employer.",
    "identificationMarks may contain one or two concise natural identifying marks. If none are used, return an empty string.",
    "nomineeName and nomineeRelationship must describe one plausible nominated person and the relationship must be consistent with the member's family scenario.",
    "fingerprintCertificationDate and divisionalSecretaryDate must use YYYY-MM-DD and should be chronologically plausible.",
    "certifyingOfficerDivisionNumber should be a short plausible division/area number suitable for a Grama Niladhari certification.",
    "Keep all generated text concise enough to fit naturally within the corresponding dotted-line bounding boxes.",
    "Use only synthetic personal, family, employment, membership, and address information. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys defined in the fields array. Do not invent additional ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, fingerprints, signatures, or stamps. Those are already represented in the static annotation template.",
    "leftFingerprint, rightFingerprint, memberSignature, employerOrGramaNiladhariSignature, divisionalSecretarySignature, divisionalSecretaryStamp, certifyingOfficerSignature, and certifyingOfficerStamp are image-style annotation regions and should not be returned as ordinary text values unless the rendering pipeline explicitly supports synthetic image assets."
  ],

  fields: [
    {
      key: "memberName",
      labelSi: "සාමාජිකයාගේ නම",
      labelEn: "Member Name",
      type: "text",
      required: true,
    },
    {
      key: "memberNumber",
      labelSi: "සාමාජික අංකය",
      labelEn: "Member Number",
      type: "text",
      required: true,
    },
    {
      key: "memberAddress",
      labelSi: "ලිපිනය",
      labelEn: "Address",
      type: "address",
      required: true,
    },
    {
      key: "memberAge",
      labelSi: "වයස",
      labelEn: "Age",
      type: "number",
      required: true,
    },
    {
      key: "dateOfBirth",
      labelSi: "උපන් දිනය",
      labelEn: "Date of Birth",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "maritalStatus",
      labelSi: "විවාහක / අවිවාහක තත්ත්වය",
      labelEn: "Marital Status",
      type: "text",
      required: true,
      helpTextSi: "විවාහක / අවිවාහක ලෙස සඳහන් කරන්න.",
    },
    {
      key: "nationalIdentityCardNumber",
      labelSi: "ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "National Identity Card Number",
      type: "nic",
      required: true,
    },
    {
      key: "fatherName",
      labelSi: "පියාගේ නම",
      labelEn: "Father's Name",
      type: "text",
      required: true,
    },
    {
      key: "fatherDateOfBirth",
      labelSi: "පියාගේ උපන් දිනය",
      labelEn: "Father's Date of Birth",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "motherName",
      labelSi: "මවගේ නම",
      labelEn: "Mother's Name",
      type: "text",
      required: true,
    },
    {
      key: "motherDateOfBirth",
      labelSi: "මවගේ උපන් දිනය",
      labelEn: "Mother's Date of Birth",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "spouseName",
      labelSi: "විවාහ වී ඇත්නම් ස්වාමිපුරුෂයාගේ / භාර්යාවගේ නම",
      labelEn: "Spouse Name",
      type: "text",
      required: false,
    },
    {
      key: "employerOrEstateName",
      labelSi: "සේවය කළ ආයතනයේ හෝ වත්තේ නම",
      labelEn: "Employer / Estate Name",
      type: "text",
      required: true,
    },
    {
      key: "occupationStatus",
      labelSi: "රක්ෂාවේ තරාතිරම",
      labelEn: "Occupation / Employment Status",
      type: "text",
      required: true,
    },
    {
      key: "identificationMarks",
      labelSi: "හඳුනාගැනීමේ ස්වාභාවික ලකුණු",
      labelEn: "Natural Identification Marks",
      type: "text",
      required: false,
    },
    {
      key: "nomineeName",
      labelSi: "නම් කරන ලද තැනැත්තාගේ නම",
      labelEn: "Nominee Name",
      type: "text",
      required: true,
    },
    {
      key: "nomineeRelationship",
      labelSi: "නම් කරන ලද තැනැත්තා සමඟ ඇති ඥාති සම්බන්ධතාවය",
      labelEn: "Relationship to Nominee",
      type: "text",
      required: true,
    },
    {
      key: "fingerprintCertificationDate",
      labelSi: "ඇඟිලි සලකුණු සහතික කළ දිනය",
      labelEn: "Fingerprint Certification Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "divisionalSecretaryDate",
      labelSi: "ප්‍රාදේශීය ලේකම් සහතිකයේ දිනය",
      labelEn: "Divisional Secretary Certification Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "certifyingOfficerDivisionNumber",
      labelSi: "ග්‍රාම නිලධාරී කොට්ඨාස අංකය",
      labelEn: "Certifying Officer Division Number",
      type: "text",
      required: true,
    },
  ],
};
