import { EDUCATION_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const alVocationalStreamGrade12ApplicationFormDefinition: DataCollectionForm = {
  id: "al-vocational-stream-grade-12-application-2026",
  nameSi: "12 ශ්‍රේණියට ඇතුළත් වීම සඳහා අයදුම් පත්‍රය - 2026",
  nameEn: "Grade 12 Admission Application - A/L Vocational Stream 2026",
  documentPath:
    "/forms/education/al-vocational-stream-grade-12-application-2026.pdf",
  category: EDUCATION_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds to one or more {{fieldKey}} placeholders or printed-choice controls in the static OCR/layout annotation template.",
    "When applying generated values, replace only matching placeholders or resolve the corresponding printed choice. Do not modify fixed OCR text, bounding boxes, labels, reading order, page numbers, table structure, footnotes, or other layout metadata.",
    "Generate one internally consistent synthetic Sri Lankan Grade 12 applicant for the 2026 G.C.E. A/L Vocational Stream application.",
    "studentFullName and nameWithInitials must refer to the same student.",
    "permanentAddress must be a plausible synthetic Sri Lankan address.",
    "phoneNumber and whatsAppNumber must be plausible synthetic Sri Lankan mobile/contact numbers. They may be the same if desired.",
    "sex should be a concise value consistent with the printed form.",
    "mediumOfStudy must be a plausible school medium such as සිංහල or දෙමළ.",
    "dateOfBirth must use YYYY-MM-DD.",
    "ageYears, ageMonths, and ageDays must exactly match dateOfBirth as at 2025-01-31.",
    "preferredVocationalMedium must be exactly සිංහල or දෙමළ and should be rendered by retaining the corresponding printed option.",
    "vocationalSubjectChoice1, vocationalSubjectChoice2, and vocationalSubjectChoice3 must be three different plausible vocational subjects from the programme.",
    "olSchoolAddress, olSchoolDistrict, and olSchoolAdmissionNumber must refer to the same previous school record.",
    "olExamYear and olExamIndexNumber must be plausible and chronologically consistent with the student's age.",
    "Populate the O/L result rows consecutively. Each populated olSubjectNName must have a corresponding olSubjectNGrade.",
    "Every O/L grade must be exactly A, B, C, S, or W, matching the grade symbols printed on the form.",
    "coCurricularAchievements should be concise, plausible school-level achievements. If none are used, return an empty string.",
    "parentGuardianNameAndAddress must be plausible and consistent with the student's family and residential context.",
    "studentDeclarationDate and parentGuardianDeclarationDate must use YYYY-MM-DD and should normally be the same or very close dates.",
    "currentGrade must represent the student's current/recent grade as certified by the school.",
    "schoolLowestGrade and schoolHighestGrade must describe a plausible grade range offered by the current school.",
    "vocationalStreamImplemented must be exactly ක්‍රියාත්මක කරනු ලබන or ක්‍රියාත්මක කරනු නොලබන. It is a printed-choice control.",
    "If vocationalStreamImplemented indicates that the stream is implemented, populate one or more offeredVocationalSubject fields consecutively from subject 1. If it is not implemented, return empty strings for all offeredVocationalSubject fields.",
    "principalNotes may be empty or contain a short realistic certification note.",
    "principalCertificationDate must use YYYY-MM-DD and must be chronologically consistent with the application/declaration dates.",
    "Keep all generated values concise enough to fit naturally inside their assigned bounding boxes.",
    "Use only synthetic student, parent/guardian, school, contact, examination, and educational data. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys defined in the fields array. Do not invent additional ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, signatures, or stamps. Those are already represented in the static annotation template.",
    "studentSignature, parentGuardianSignature, principalSignature, and principalOfficialStamp are image-style annotation regions and should not be returned as ordinary text values unless the rendering pipeline explicitly supports synthetic image assets."
  ],

  fields: [
    {
      key: "studentFullName",
      labelSi: "ශිෂ්‍යයාගේ / ශිෂ්‍යාවගේ සම්පූර්ණ නම",
      labelEn: "Student Full Name",
      type: "text",
      required: true,
    },
    {
      key: "nameWithInitials",
      labelSi: "මුලකුරු සමග නම",
      labelEn: "Name with Initials",
      type: "text",
      required: true,
    },
    {
      key: "permanentAddress",
      labelSi: "ස්ථීර ලිපිනය",
      labelEn: "Permanent Address",
      type: "address",
      required: true,
    },
    {
      key: "phoneNumber",
      labelSi: "දුරකතන අංකය",
      labelEn: "Telephone Number",
      type: "phone",
      required: true,
    },
    {
      key: "whatsAppNumber",
      labelSi: "WhatsApp අංකය",
      labelEn: "WhatsApp Number",
      type: "phone",
      required: true,
    },
    {
      key: "sex",
      labelSi: "ස්ත්‍රී / පුරුෂ භාවය",
      labelEn: "Sex",
      type: "text",
      required: true,
    },
    {
      key: "mediumOfStudy",
      labelSi: "ඉගෙනුම් මාධ්‍යය",
      labelEn: "Medium of Study",
      type: "text",
      required: true,
    },
    {
      key: "dateOfBirth",
      labelSi: "උපන් දිනය",
      labelEn: "Date of Birth",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "ageYears",
      labelSi: "2025 ජනවාරි 31 දිනට වයස - අවුරුදු",
      labelEn: "Age as at 2025-01-31 - Years",
      type: "number",
      required: true,
    },
    {
      key: "ageMonths",
      labelSi: "2025 ජනවාරි 31 දිනට වයස - මාස",
      labelEn: "Age as at 2025-01-31 - Months",
      type: "number",
      required: true,
    },
    {
      key: "ageDays",
      labelSi: "2025 ජනවාරි 31 දිනට වයස - දින",
      labelEn: "Age as at 2025-01-31 - Days",
      type: "number",
      required: true,
    },
    {
      key: "preferredVocationalMedium",
      labelSi: "වෘත්තීය විෂය ධාරාව ඉගෙනීමට අදහස් කරන මාධ්‍යය",
      labelEn: "Preferred Medium for Vocational Stream",
      type: "text",
      required: true,
      helpTextSi: "සිංහල / දෙමළ ලෙස සඳහන් කරන්න.",
    },
    {
      key: "vocationalSubjectChoice1",
      labelSi: "තෝරාගත් වෘත්තීය විෂය 1",
      labelEn: "Vocational Subject Choice 1",
      type: "text",
      required: true,
    },
    {
      key: "vocationalSubjectChoice2",
      labelSi: "තෝරාගත් වෘත්තීය විෂය 2",
      labelEn: "Vocational Subject Choice 2",
      type: "text",
      required: true,
    },
    {
      key: "vocationalSubjectChoice3",
      labelSi: "තෝරාගත් වෘත්තීය විෂය 3",
      labelEn: "Vocational Subject Choice 3",
      type: "text",
      required: true,
    },
    {
      key: "olSchoolAddress",
      labelSi: "සාමාන්‍ය පෙළ ඉගෙනුම ලැබූ පාසලේ ලිපිනය",
      labelEn: "Address of O/L School",
      type: "address",
      required: true,
    },
    {
      key: "olSchoolDistrict",
      labelSi: "එම පාසල පිහිටි දිස්ත්‍රික්කය",
      labelEn: "District of O/L School",
      type: "text",
      required: true,
    },
    {
      key: "olSchoolAdmissionNumber",
      labelSi: "පාසල් ඇතුළත් වීමේ අංකය",
      labelEn: "School Admission Number",
      type: "text",
      required: true,
    },
    {
      key: "olExamYear",
      labelSi: "සාමාන්‍ය පෙළ විභාග වර්ෂය",
      labelEn: "O/L Examination Year",
      type: "number",
      required: true,
    },
    {
      key: "olExamIndexNumber",
      labelSi: "සාමාන්‍ය පෙළ විභාග අංකය",
      labelEn: "O/L Examination Index Number",
      type: "text",
      required: true,
    },

    {
      key: "olSubject1Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 1",
      labelEn: "O/L Subject 1",
      type: "text",
      required: false,
    },
    {
      key: "olSubject1Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 1 ශ්‍රේණිය",
      labelEn: "O/L Subject 1 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject2Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 2",
      labelEn: "O/L Subject 2",
      type: "text",
      required: false,
    },
    {
      key: "olSubject2Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 2 ශ්‍රේණිය",
      labelEn: "O/L Subject 2 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject3Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 3",
      labelEn: "O/L Subject 3",
      type: "text",
      required: false,
    },
    {
      key: "olSubject3Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 3 ශ්‍රේණිය",
      labelEn: "O/L Subject 3 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject4Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 4",
      labelEn: "O/L Subject 4",
      type: "text",
      required: false,
    },
    {
      key: "olSubject4Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 4 ශ්‍රේණිය",
      labelEn: "O/L Subject 4 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject5Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 5",
      labelEn: "O/L Subject 5",
      type: "text",
      required: false,
    },
    {
      key: "olSubject5Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 5 ශ්‍රේණිය",
      labelEn: "O/L Subject 5 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject6Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 6",
      labelEn: "O/L Subject 6",
      type: "text",
      required: false,
    },
    {
      key: "olSubject6Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 6 ශ්‍රේණිය",
      labelEn: "O/L Subject 6 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject7Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 7",
      labelEn: "O/L Subject 7",
      type: "text",
      required: false,
    },
    {
      key: "olSubject7Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 7 ශ්‍රේණිය",
      labelEn: "O/L Subject 7 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject8Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 8",
      labelEn: "O/L Subject 8",
      type: "text",
      required: false,
    },
    {
      key: "olSubject8Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 8 ශ්‍රේණිය",
      labelEn: "O/L Subject 8 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },
    {
      key: "olSubject9Name",
      labelSi: "සාමාන්‍ය පෙළ විෂය 9",
      labelEn: "O/L Subject 9",
      type: "text",
      required: false,
    },
    {
      key: "olSubject9Grade",
      labelSi: "සාමාන්‍ය පෙළ විෂය 9 ශ්‍රේණිය",
      labelEn: "O/L Subject 9 Grade",
      type: "text",
      required: false,
      helpTextSi: "A / B / C / S / W ලෙස සඳහන් කරන්න.",
    },

    {
      key: "coCurricularAchievements",
      labelSi: "විෂය සමගාමී ජයග්‍රහණ",
      labelEn: "Co-curricular Achievements",
      type: "text",
      required: false,
    },
    {
      key: "parentGuardianNameAndAddress",
      labelSi: "මව / පියා / භාරකරුගේ නම සහ ලිපිනය",
      labelEn: "Parent / Guardian Name and Address",
      type: "address",
      required: true,
    },
    {
      key: "studentDeclarationDate",
      labelSi: "ශිෂ්‍යයාගේ / ශිෂ්‍යාවගේ අත්සන් දිනය",
      labelEn: "Student Declaration Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "parentGuardianDeclarationDate",
      labelSi: "පියාගේ / මවගේ / භාරකරුගේ අත්සන් දිනය",
      labelEn: "Parent / Guardian Declaration Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "currentGrade",
      labelSi: "දැනට ඉගෙනුම ලබන ශ්‍රේණිය",
      labelEn: "Current Grade",
      type: "text",
      required: true,
    },
    {
      key: "schoolLowestGrade",
      labelSi: "විදුහලේ ඉගැන්වීම ආරම්භ වන ශ්‍රේණිය",
      labelEn: "Lowest Grade Offered by School",
      type: "text",
      required: true,
    },
    {
      key: "schoolHighestGrade",
      labelSi: "විදුහලේ ඉගැන්වීම අවසන් වන ශ්‍රේණිය",
      labelEn: "Highest Grade Offered by School",
      type: "text",
      required: true,
    },
    {
      key: "vocationalStreamImplemented",
      labelSi: "උසස් පෙළ වෘත්තීය විෂය ධාරාව ක්‍රියාත්මක කරන්නේද",
      labelEn: "Whether A/L Vocational Stream Is Implemented",
      type: "text",
      required: true,
    },

    {
      key: "offeredVocationalSubject1",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 1",
      labelEn: "Vocational Subject Offered by School 1",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject2",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 2",
      labelEn: "Vocational Subject Offered by School 2",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject3",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 3",
      labelEn: "Vocational Subject Offered by School 3",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject4",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 4",
      labelEn: "Vocational Subject Offered by School 4",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject5",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 5",
      labelEn: "Vocational Subject Offered by School 5",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject6",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 6",
      labelEn: "Vocational Subject Offered by School 6",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject7",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 7",
      labelEn: "Vocational Subject Offered by School 7",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject8",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 8",
      labelEn: "Vocational Subject Offered by School 8",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject9",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 9",
      labelEn: "Vocational Subject Offered by School 9",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject10",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 10",
      labelEn: "Vocational Subject Offered by School 10",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject11",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 11",
      labelEn: "Vocational Subject Offered by School 11",
      type: "text",
      required: false,
    },
    {
      key: "offeredVocationalSubject12",
      labelSi: "විදුහලේ ඉගැන්වෙන වෘත්තීය විෂය 12",
      labelEn: "Vocational Subject Offered by School 12",
      type: "text",
      required: false,
    },

    {
      key: "principalNotes",
      labelSi: "විදුහල්පතිගේ සටහන්",
      labelEn: "Principal Notes",
      type: "text",
      required: false,
    },
    {
      key: "principalCertificationDate",
      labelSi: "විදුහල්පති සහතික කළ දිනය",
      labelEn: "Principal Certification Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
  ],
};
