import { EDUCATION_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const gradeOneAdmissionAffidavitFormDefinition: DataCollectionForm = {
  id: "grade-one-admission-affidavit",
  nameSi: "පළමු ශ්‍රේණියට ඇතුළත් කිරීම සඳහා දිවුරුම් ප්‍රකාශය",
  nameEn: "Grade 01 Admission Affidavit",
  documentPath:
    "/forms/education/grade-one-admission-affidavit.pdf",
  category: EDUCATION_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds either to a {{fieldKey}} placeholder or to a printed choice-control region in the static OCR/layout annotation template.",
    "When applying generated values, replace only matching placeholders or resolve the matching printed choice. Do not modify fixed OCR text, bounding boxes, labels, reading order, page number, headings, or other layout metadata.",
    "Generate one internally consistent synthetic Sri Lankan Grade 01 school-admission affidavit scenario.",
    "declarantProvince, declarantDistrict, declarantAddress, and declarantName must describe one plausible synthetic parent or legal guardian.",
    "declarantName must not refer to a real public figure.",
    "declarantEthnicity must be one of the alternatives represented on the printed form, such as සිංහල, දෙමළ, or මුස්ලිම්. It is a rendering-control value; retain the matching printed alternative and delete/strike the others rather than printing the control value over the form.",
    "declarantReligion must correspond to one of the religious alternatives printed on the form. It is a rendering-control value and should be used to retain only the applicable printed alternative.",
    "childName must be a plausible synthetic child name consistent with the declarant's family scenario.",
    "schoolName must be a plausible Sri Lankan school name.",
    "admissionGrade should be 1 or an equivalent concise value appropriate for a Grade 01 admission affidavit.",
    "The form contains 28 supporting-document rows. Generate only document references that make sense for the synthetic scenario.",
    "document01Number through document28Number represent the reference/serial numbers written into the corresponding numbered supporting-document rows.",
    "If a supporting-document row is not applicable, return an empty string for its documentXXNumber field so the dotted line remains visually blank.",
    "Items 16, 17, 18, and 28 contain an additional internal blank. Use document16Extra, document17Extra, document18Extra, and document28Extra only when the corresponding row is populated; otherwise return an empty string.",
    "Typical relevant evidence may include a birth certificate, parent/guardian NIC, deed or residence evidence, rates/assessment records, utility bills, Grama Niladhari residence certificates, registered letters, school/alumni evidence, transfer documentation, and foreign-residence/travel evidence, according to the fixed descriptions printed on the form.",
    "attestationDate must use YYYY-MM-DD and must be realistic. The renderer must split it into the separate year/month/day blanks in the attestation section.",
    "attestationPlace must be a plausible Sri Lankan place at which the affidavit could be signed or attested.",
    "Keep all generated values concise enough to fit naturally within their assigned dotted-line bounding boxes.",
    "Use only synthetic names, addresses, school details, and document/reference numbers. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys defined in the fields array. Do not invent additional ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, signatures, printer marks, or scan watermarks. Those are already represented in the static annotation template.",
    "declarantSignature and justiceOfPeaceOrCommissionerSignature are image-style annotation regions and should not be returned as ordinary text values unless the rendering pipeline explicitly supports synthetic signature assets."
  ],

  fields: [
    {
      key: "declarantProvince",
      labelSi: "පළාත",
      labelEn: "Province",
      type: "text",
      required: true,
    },
    {
      key: "declarantDistrict",
      labelSi: "දිස්ත්‍රික්කය",
      labelEn: "District",
      type: "text",
      required: true,
    },
    {
      key: "declarantAddress",
      labelSi: "දිවුරුම් ප්‍රකාශකයාගේ ලිපිනය",
      labelEn: "Declarant Address",
      type: "address",
      required: true,
    },
    {
      key: "declarantName",
      labelSi: "දිවුරුම් ප්‍රකාශකයාගේ නම",
      labelEn: "Declarant Name",
      type: "text",
      required: true,
    },
    {
      key: "declarantEthnicity",
      labelSi: "ජන වර්ගය",
      labelEn: "Ethnicity",
      type: "text",
      required: true,
      helpTextSi: "සිංහල / දෙමළ / මුස්ලිම් ලෙස සඳහන් කරන්න.",
    },
    {
      key: "declarantReligion",
      labelSi: "ආගම",
      labelEn: "Religion",
      type: "text",
      required: true,
    },
    {
      key: "childName",
      labelSi: "දරුවාගේ නම",
      labelEn: "Child Name",
      type: "text",
      required: true,
    },
    {
      key: "schoolName",
      labelSi: "පාසලේ නම",
      labelEn: "School Name",
      type: "text",
      required: true,
    },
    {
      key: "admissionGrade",
      labelSi: "ඇතුළත් කිරීමට ඉල්ලුම් කරන ශ්‍රේණිය",
      labelEn: "Admission Grade",
      type: "text",
      required: true,
      helpTextSi: "1 ලෙස සඳහන් කරන්න.",
    },

    // ------------------------------------------------------------
    // Supporting-document reference numbers 01-28
    // ------------------------------------------------------------
    {
      key: "document01Number",
      labelSi: "අමුණා ඇති ලේඛනය 01 - අංකය",
      labelEn: "Supporting Document 01 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document02Number",
      labelSi: "අමුණා ඇති ලේඛනය 02 - අංකය",
      labelEn: "Supporting Document 02 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document03Number",
      labelSi: "අමුණා ඇති ලේඛනය 03 - අංකය",
      labelEn: "Supporting Document 03 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document04Number",
      labelSi: "අමුණා ඇති ලේඛනය 04 - අංකය",
      labelEn: "Supporting Document 04 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document05Number",
      labelSi: "අමුණා ඇති ලේඛනය 05 - අංකය",
      labelEn: "Supporting Document 05 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document06Number",
      labelSi: "අමුණා ඇති ලේඛනය 06 - අංකය",
      labelEn: "Supporting Document 06 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document07Number",
      labelSi: "අමුණා ඇති ලේඛනය 07 - අංකය",
      labelEn: "Supporting Document 07 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document08Number",
      labelSi: "අමුණා ඇති ලේඛනය 08 - අංකය",
      labelEn: "Supporting Document 08 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document09Number",
      labelSi: "අමුණා ඇති ලේඛනය 09 - අංකය",
      labelEn: "Supporting Document 09 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document10Number",
      labelSi: "අමුණා ඇති ලේඛනය 10 - අංකය",
      labelEn: "Supporting Document 10 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document11Number",
      labelSi: "අමුණා ඇති ලේඛනය 11 - අංකය",
      labelEn: "Supporting Document 11 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document12Number",
      labelSi: "අමුණා ඇති ලේඛනය 12 - අංකය",
      labelEn: "Supporting Document 12 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document13Number",
      labelSi: "අමුණා ඇති ලේඛනය 13 - අංකය",
      labelEn: "Supporting Document 13 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document14Number",
      labelSi: "අමුණා ඇති ලේඛනය 14 - අංකය",
      labelEn: "Supporting Document 14 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document15Number",
      labelSi: "අමුණා ඇති ලේඛනය 15 - අංකය",
      labelEn: "Supporting Document 15 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document16Number",
      labelSi: "අමුණා ඇති ලේඛනය 16 - අංකය",
      labelEn: "Supporting Document 16 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document17Number",
      labelSi: "අමුණා ඇති ලේඛනය 17 - අංකය",
      labelEn: "Supporting Document 17 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document18Number",
      labelSi: "අමුණා ඇති ලේඛනය 18 - අංකය",
      labelEn: "Supporting Document 18 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document19Number",
      labelSi: "අමුණා ඇති ලේඛනය 19 - අංකය",
      labelEn: "Supporting Document 19 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document20Number",
      labelSi: "අමුණා ඇති ලේඛනය 20 - අංකය",
      labelEn: "Supporting Document 20 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document21Number",
      labelSi: "අමුණා ඇති ලේඛනය 21 - අංකය",
      labelEn: "Supporting Document 21 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document22Number",
      labelSi: "අමුණා ඇති ලේඛනය 22 - අංකය",
      labelEn: "Supporting Document 22 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document23Number",
      labelSi: "අමුණා ඇති ලේඛනය 23 - අංකය",
      labelEn: "Supporting Document 23 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document24Number",
      labelSi: "අමුණා ඇති ලේඛනය 24 - අංකය",
      labelEn: "Supporting Document 24 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document25Number",
      labelSi: "අමුණා ඇති ලේඛනය 25 - අංකය",
      labelEn: "Supporting Document 25 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document26Number",
      labelSi: "අමුණා ඇති ලේඛනය 26 - අංකය",
      labelEn: "Supporting Document 26 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document27Number",
      labelSi: "අමුණා ඇති ලේඛනය 27 - අංකය",
      labelEn: "Supporting Document 27 Reference Number",
      type: "text",
      required: false,
    },
    {
      key: "document28Number",
      labelSi: "අමුණා ඇති ලේඛනය 28 - අංකය",
      labelEn: "Supporting Document 28 Reference Number",
      type: "text",
      required: false,
    },

    // ------------------------------------------------------------
    // Secondary blanks inside specific supporting-document rows
    // ------------------------------------------------------------
    {
      key: "document16Extra",
      labelSi: "ලේඛනය 16 - අමතර විස්තරය",
      labelEn: "Supporting Document 16 - Additional Value",
      type: "text",
      required: false,
    },
    {
      key: "document17Extra",
      labelSi: "ලේඛනය 17 - අමතර විස්තරය",
      labelEn: "Supporting Document 17 - Additional Value",
      type: "text",
      required: false,
    },
    {
      key: "document18Extra",
      labelSi: "ලේඛනය 18 - අමතර විස්තරය",
      labelEn: "Supporting Document 18 - Additional Value",
      type: "text",
      required: false,
    },
    {
      key: "document28Extra",
      labelSi: "ලේඛනය 28 - අමතර විස්තරය",
      labelEn: "Supporting Document 28 - Additional Value",
      type: "text",
      required: false,
    },

    // ------------------------------------------------------------
    // Attestation
    // ------------------------------------------------------------
    {
      key: "attestationDate",
      labelSi: "දිවුරුම් ප්‍රකාශය සහතික කළ දිනය",
      labelEn: "Attestation Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "attestationPlace",
      labelSi: "දිවුරුම් ප්‍රකාශය සහතික කළ ස්ථානය",
      labelEn: "Attestation Place",
      type: "text",
      required: true,
    },
  ],
};
