import { EDUCATION_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const gradeOneAdmissionFormDefinition: DataCollectionForm = {
  id: "grade-one-admission-form-2024",
  nameSi: "2024 පළමු ශ්‍රේණියට ඇතුළත් කිරීම සඳහා අයදුම් පත්‍රය",
  nameEn: "Grade 01 Admission Application Form - 2024",
  documentPath: "/forms/education/grade-one-admission-form-2024.pdf",
  category: EDUCATION_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds to one or more {{fieldKey}} placeholders or choice-control regions in the static OCR/layout annotation template.",
    "When applying generated values, replace only matching placeholders or resolve the matching printed alternatives. Do not modify fixed OCR text, bounding boxes, labels, reading order, page numbers, table structure, headings, office-use-only marks columns, printer marks, or scan watermarks.",
    "Generate one internally consistent synthetic Grade 01 school-admission scenario for a Sri Lankan child and parent/legal-guardian household.",
    "schoolName and requestedSchoolName should refer to the same school.",
    "childFullName, childNameWithInitialsSinhala, and childNameWithInitialsEnglish must refer to the same child.",
    "childGender, childReligion, childMedium, birthYear, birthMonth, birthDay, ageYearsAt20240131, ageMonthsAt20240131, and ageDaysAt20240131 must be mutually consistent.",
    "The age fields must correctly represent the child's age as at 2024-01-31.",
    "Applicant details must describe one synthetic parent/legal guardian. Spouse details, when used, must describe one internally consistent spouse.",
    "NIC numbers, addresses and telephone numbers must be synthetic and plausible.",
    "Preferred-school rows should be populated consecutively from preferredSchool1 and distances should be plausible.",
    "closerSchool1 through closerSchool10 are optional and should be left as empty strings when unused.",
    "The five electoral-register blocks must form a coherent household and residence history.",
    "Pages 3 and 4 contain alternative selection-category criteria. Populate only the criteria relevant to the synthetic application and return empty strings for irrelevant criteria.",
    "If the sibling category is used, populate sibling rows consecutively and keep each row internally consistent.",
    "If an education-service or transfer category is used, service history, locations, dates, leave days, and distances must be chronologically and geographically consistent.",
    "If the returned-from-abroad category is used, the country, period and reason must form one plausible scenario.",
    "applicationDate and declarationDate must use YYYY-MM-DD and be chronologically consistent.",
    "Keep generated values concise enough to fit naturally within their assigned bounding boxes.",
    "Return values using exactly the field keys defined in the fields array.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, points, office-use-only values, signatures, printer marks, or scan watermarks.",
    "applicantSignature and parentGuardianSignature are separate Signature regions and should not be returned as ordinary text values unless the rendering pipeline supports synthetic signature assets."
  ],

  fields: [
    { key: "schoolName", labelSi: "පාසලේ නම", labelEn: "School Name", type: "text", required: true },
    { key: "requestedSchoolName", labelSi: "ඉල්ලුම් කරන පාසල", labelEn: "Requested School", type: "text", required: true },

    { key: "childFullName", labelSi: "ළමයාගේ සම්පූර්ණ නම", labelEn: "Child Full Name", type: "text", required: true },
    { key: "childNameWithInitialsSinhala", labelSi: "මුලකුරු සමග නම - සිංහල", labelEn: "Name with Initials - Sinhala", type: "text", required: true },
    { key: "childNameWithInitialsEnglish", labelSi: "මුලකුරු සමග නම - ඉංග්‍රීසි", labelEn: "Name with Initials - English", type: "text", required: true },
    { key: "childGender", labelSi: "ස්ත්‍රී / පුරුෂ භාවය", labelEn: "Gender", type: "text", required: true },
    { key: "childReligion", labelSi: "ආගම", labelEn: "Religion", type: "text", required: true },
    { key: "childMedium", labelSi: "ඉගෙනුම් මාධ්‍යය", labelEn: "Medium of Study", type: "text", required: true },
    { key: "birthYear", labelSi: "උපන් වර්ෂය", labelEn: "Birth Year", type: "number", required: true },
    { key: "birthMonth", labelSi: "උපන් මාසය", labelEn: "Birth Month", type: "number", required: true },
    { key: "birthDay", labelSi: "උපන් දිනය", labelEn: "Birth Day", type: "number", required: true },
    { key: "ageYearsAt20240131", labelSi: "2024-01-31 දිනට වයස - අවුරුදු", labelEn: "Age at 2024-01-31 - Years", type: "number", required: true },
    { key: "ageMonthsAt20240131", labelSi: "2024-01-31 දිනට වයස - මාස", labelEn: "Age at 2024-01-31 - Months", type: "number", required: true },
    { key: "ageDaysAt20240131", labelSi: "2024-01-31 දිනට වයස - දින", labelEn: "Age at 2024-01-31 - Days", type: "number", required: true },

    { key: "applicantFullName", labelSi: "අයදුම්කරුගේ සම්පූර්ණ නම", labelEn: "Applicant Full Name", type: "text", required: true },
    { key: "spouseFullName", labelSi: "කලත්‍රයාගේ සම්පූර්ණ නම", labelEn: "Spouse Full Name", type: "text", required: false },
    { key: "applicantNameWithInitials", labelSi: "අයදුම්කරුගේ මුලකුරු සමග නම", labelEn: "Applicant Name with Initials", type: "text", required: true },
    { key: "spouseNameWithInitials", labelSi: "කලත්‍රයාගේ මුලකුරු සමග නම", labelEn: "Spouse Name with Initials", type: "text", required: false },
    { key: "applicantNicNumber", labelSi: "අයදුම්කරුගේ ජාතික හැඳුනුම්පත් අංකය", labelEn: "Applicant NIC Number", type: "nic", required: true },
    { key: "spouseNicNumber", labelSi: "කලත්‍රයාගේ ජාතික හැඳුනුම්පත් අංකය", labelEn: "Spouse NIC Number", type: "nic", required: false },
    { key: "applicantSriLankanCitizen", labelSi: "අයදුම්කරු ශ්‍රී ලාංකිකයෙක් ද", labelEn: "Applicant is Sri Lankan", type: "text", required: true },
    { key: "spouseSriLankanCitizen", labelSi: "කලත්‍රයා ශ්‍රී ලාංකිකයෙක් ද", labelEn: "Spouse is Sri Lankan", type: "text", required: false },
    { key: "applicantReligion", labelSi: "අයදුම්කරුගේ ආගම", labelEn: "Applicant Religion", type: "text", required: true },
    { key: "spouseReligion", labelSi: "කලත්‍රයාගේ ආගම", labelEn: "Spouse Religion", type: "text", required: false },
    { key: "applicantPermanentAddress", labelSi: "අයදුම්කරුගේ ස්ථිර ලිපිනය", labelEn: "Applicant Permanent Address", type: "address", required: true },
    { key: "spousePermanentAddress", labelSi: "කලත්‍රයාගේ ස්ථිර ලිපිනය", labelEn: "Spouse Permanent Address", type: "address", required: false },
    { key: "applicantPhoneNumber", labelSi: "අයදුම්කරුගේ දුරකථන අංකය", labelEn: "Applicant Phone Number", type: "phone", required: true },
    { key: "spousePhoneNumber", labelSi: "කලත්‍රයාගේ දුරකථන අංකය", labelEn: "Spouse Phone Number", type: "phone", required: false },
    { key: "applicantDistrict", labelSi: "අයදුම්කරු පදිංචි දිස්ත්‍රික්කය", labelEn: "Applicant District", type: "text", required: true },
    { key: "spouseDistrict", labelSi: "කලත්‍රයා පදිංචි දිස්ත්‍රික්කය", labelEn: "Spouse District", type: "text", required: false },
    { key: "applicantDivisionalSecretariat", labelSi: "අයදුම්කරුගේ ප්‍රාදේශීය ලේකම් කොට්ඨාසය", labelEn: "Applicant Divisional Secretariat", type: "text", required: true },
    { key: "spouseDivisionalSecretariat", labelSi: "කලත්‍රයාගේ ප්‍රාදේශීය ලේකම් කොට්ඨාසය", labelEn: "Spouse Divisional Secretariat", type: "text", required: false },
    { key: "applicantGnDivision", labelSi: "අයදුම්කරුගේ ග්‍රාම නිලධාරි වසම / අංකය", labelEn: "Applicant GN Division / Number", type: "text", required: true },
    { key: "spouseGnDivision", labelSi: "කලත්‍රයාගේ ග්‍රාම නිලධාරි වසම / අංකය", labelEn: "Spouse GN Division / Number", type: "text", required: false },

    {
      key: "preferredSchool1Name",
      labelSi: "කැමැත්ත අනුව පාසල 1 - නම",
      labelEn: "Preferred School 1 - Name",
      type: "text",
      required: true,
    },
    {
      key: "preferredSchool1Type",
      labelSi: "කැමැත්ත අනුව පාසල 1 - වර්ගය",
      labelEn: "Preferred School 1 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool1DistanceKm",
      labelSi: "කැමැත්ත අනුව පාසල 1 - දුර (කි.මී.)",
      labelEn: "Preferred School 1 - Distance (km)",
      type: "number",
      required: false,
    },
    {
      key: "preferredSchool2Name",
      labelSi: "කැමැත්ත අනුව පාසල 2 - නම",
      labelEn: "Preferred School 2 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool2Type",
      labelSi: "කැමැත්ත අනුව පාසල 2 - වර්ගය",
      labelEn: "Preferred School 2 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool2DistanceKm",
      labelSi: "කැමැත්ත අනුව පාසල 2 - දුර (කි.මී.)",
      labelEn: "Preferred School 2 - Distance (km)",
      type: "number",
      required: false,
    },
    {
      key: "preferredSchool3Name",
      labelSi: "කැමැත්ත අනුව පාසල 3 - නම",
      labelEn: "Preferred School 3 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool3Type",
      labelSi: "කැමැත්ත අනුව පාසල 3 - වර්ගය",
      labelEn: "Preferred School 3 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool3DistanceKm",
      labelSi: "කැමැත්ත අනුව පාසල 3 - දුර (කි.මී.)",
      labelEn: "Preferred School 3 - Distance (km)",
      type: "number",
      required: false,
    },
    {
      key: "preferredSchool4Name",
      labelSi: "කැමැත්ත අනුව පාසල 4 - නම",
      labelEn: "Preferred School 4 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool4Type",
      labelSi: "කැමැත්ත අනුව පාසල 4 - වර්ගය",
      labelEn: "Preferred School 4 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool4DistanceKm",
      labelSi: "කැමැත්ත අනුව පාසල 4 - දුර (කි.මී.)",
      labelEn: "Preferred School 4 - Distance (km)",
      type: "number",
      required: false,
    },
    {
      key: "preferredSchool5Name",
      labelSi: "කැමැත්ත අනුව පාසල 5 - නම",
      labelEn: "Preferred School 5 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool5Type",
      labelSi: "කැමැත්ත අනුව පාසල 5 - වර්ගය",
      labelEn: "Preferred School 5 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool5DistanceKm",
      labelSi: "කැමැත්ත අනුව පාසල 5 - දුර (කි.මී.)",
      labelEn: "Preferred School 5 - Distance (km)",
      type: "number",
      required: false,
    },
    {
      key: "preferredSchool6Name",
      labelSi: "කැමැත්ත අනුව පාසල 6 - නම",
      labelEn: "Preferred School 6 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool6Type",
      labelSi: "කැමැත්ත අනුව පාසල 6 - වර්ගය",
      labelEn: "Preferred School 6 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool6DistanceKm",
      labelSi: "කැමැත්ත අනුව පාසල 6 - දුර (කි.මී.)",
      labelEn: "Preferred School 6 - Distance (km)",
      type: "number",
      required: false,
    },
    {
      key: "closerSchool1",
      labelSi: "ආසන්න වෙනත් පාසල 1",
      labelEn: "Closer Alternative School 1",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool2",
      labelSi: "ආසන්න වෙනත් පාසල 2",
      labelEn: "Closer Alternative School 2",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool3",
      labelSi: "ආසන්න වෙනත් පාසල 3",
      labelEn: "Closer Alternative School 3",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool4",
      labelSi: "ආසන්න වෙනත් පාසල 4",
      labelEn: "Closer Alternative School 4",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool5",
      labelSi: "ආසන්න වෙනත් පාසල 5",
      labelEn: "Closer Alternative School 5",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool6",
      labelSi: "ආසන්න වෙනත් පාසල 6",
      labelEn: "Closer Alternative School 6",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool7",
      labelSi: "ආසන්න වෙනත් පාසල 7",
      labelEn: "Closer Alternative School 7",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool8",
      labelSi: "ආසන්න වෙනත් පාසල 8",
      labelEn: "Closer Alternative School 8",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool9",
      labelSi: "ආසන්න වෙනත් පාසල 9",
      labelEn: "Closer Alternative School 9",
      type: "text",
      required: false,
    },
    {
      key: "closerSchool10",
      labelSi: "ආසන්න වෙනත් පාසල 10",
      labelEn: "Closer Alternative School 10",
      type: "text",
      required: false,
    },
    {
      key: "electoralYear1",
      labelSi: "ඡන්ද හිමි නාමලේඛනය - වර්ෂය 1",
      labelEn: "Electoral Register Year 1",
      type: "number",
      required: false,
    },
    {
      key: "electoralDistrict1",
      labelSi: "ඡන්ද ප්‍රදේශය 1",
      labelEn: "Electoral District 1",
      type: "text",
      required: false,
    },
    {
      key: "electoralGnDivision1",
      labelSi: "ග්‍රාම නිලධාරි වසම හා අංකය 1",
      labelEn: "GN Division and Number 1",
      type: "text",
      required: false,
    },
    {
      key: "electoralPollingDivision1",
      labelSi: "ඡන්ද කොට්ඨාශය 1",
      labelEn: "Polling Division 1",
      type: "text",
      required: false,
    },
    {
      key: "electoralVillageStreetEstate1",
      labelSi: "ගම / වීදිය / වත්ත 1",
      labelEn: "Village / Street / Estate 1",
      type: "text",
      required: false,
    },
    {
      key: "electoralHouseholdNumber1",
      labelSi: "ගෘහ / පදිංචි අංකය 1",
      labelEn: "Household / Residence Number 1",
      type: "text",
      required: false,
    },
    {
      key: "electoralRegisteredNames1",
      labelSi: "ඡන්ද හිමි නාමලේඛනයේ නම් 1",
      labelEn: "Names in Electoral Register 1",
      type: "text",
      required: false,
    },
    {
      key: "electoralYear2",
      labelSi: "ඡන්ද හිමි නාමලේඛනය - වර්ෂය 2",
      labelEn: "Electoral Register Year 2",
      type: "number",
      required: false,
    },
    {
      key: "electoralDistrict2",
      labelSi: "ඡන්ද ප්‍රදේශය 2",
      labelEn: "Electoral District 2",
      type: "text",
      required: false,
    },
    {
      key: "electoralGnDivision2",
      labelSi: "ග්‍රාම නිලධාරි වසම හා අංකය 2",
      labelEn: "GN Division and Number 2",
      type: "text",
      required: false,
    },
    {
      key: "electoralPollingDivision2",
      labelSi: "ඡන්ද කොට්ඨාශය 2",
      labelEn: "Polling Division 2",
      type: "text",
      required: false,
    },
    {
      key: "electoralVillageStreetEstate2",
      labelSi: "ගම / වීදිය / වත්ත 2",
      labelEn: "Village / Street / Estate 2",
      type: "text",
      required: false,
    },
    {
      key: "electoralHouseholdNumber2",
      labelSi: "ගෘහ / පදිංචි අංකය 2",
      labelEn: "Household / Residence Number 2",
      type: "text",
      required: false,
    },
    {
      key: "electoralRegisteredNames2",
      labelSi: "ඡන්ද හිමි නාමලේඛනයේ නම් 2",
      labelEn: "Names in Electoral Register 2",
      type: "text",
      required: false,
    },
    {
      key: "electoralYear3",
      labelSi: "ඡන්ද හිමි නාමලේඛනය - වර්ෂය 3",
      labelEn: "Electoral Register Year 3",
      type: "number",
      required: false,
    },
    {
      key: "electoralDistrict3",
      labelSi: "ඡන්ද ප්‍රදේශය 3",
      labelEn: "Electoral District 3",
      type: "text",
      required: false,
    },
    {
      key: "electoralGnDivision3",
      labelSi: "ග්‍රාම නිලධාරි වසම හා අංකය 3",
      labelEn: "GN Division and Number 3",
      type: "text",
      required: false,
    },
    {
      key: "electoralPollingDivision3",
      labelSi: "ඡන්ද කොට්ඨාශය 3",
      labelEn: "Polling Division 3",
      type: "text",
      required: false,
    },
    {
      key: "electoralVillageStreetEstate3",
      labelSi: "ගම / වීදිය / වත්ත 3",
      labelEn: "Village / Street / Estate 3",
      type: "text",
      required: false,
    },
    {
      key: "electoralHouseholdNumber3",
      labelSi: "ගෘහ / පදිංචි අංකය 3",
      labelEn: "Household / Residence Number 3",
      type: "text",
      required: false,
    },
    {
      key: "electoralRegisteredNames3",
      labelSi: "ඡන්ද හිමි නාමලේඛනයේ නම් 3",
      labelEn: "Names in Electoral Register 3",
      type: "text",
      required: false,
    },
    {
      key: "electoralYear4",
      labelSi: "ඡන්ද හිමි නාමලේඛනය - වර්ෂය 4",
      labelEn: "Electoral Register Year 4",
      type: "number",
      required: false,
    },
    {
      key: "electoralDistrict4",
      labelSi: "ඡන්ද ප්‍රදේශය 4",
      labelEn: "Electoral District 4",
      type: "text",
      required: false,
    },
    {
      key: "electoralGnDivision4",
      labelSi: "ග්‍රාම නිලධාරි වසම හා අංකය 4",
      labelEn: "GN Division and Number 4",
      type: "text",
      required: false,
    },
    {
      key: "electoralPollingDivision4",
      labelSi: "ඡන්ද කොට්ඨාශය 4",
      labelEn: "Polling Division 4",
      type: "text",
      required: false,
    },
    {
      key: "electoralVillageStreetEstate4",
      labelSi: "ගම / වීදිය / වත්ත 4",
      labelEn: "Village / Street / Estate 4",
      type: "text",
      required: false,
    },
    {
      key: "electoralHouseholdNumber4",
      labelSi: "ගෘහ / පදිංචි අංකය 4",
      labelEn: "Household / Residence Number 4",
      type: "text",
      required: false,
    },
    {
      key: "electoralRegisteredNames4",
      labelSi: "ඡන්ද හිමි නාමලේඛනයේ නම් 4",
      labelEn: "Names in Electoral Register 4",
      type: "text",
      required: false,
    },
    {
      key: "electoralYear5",
      labelSi: "ඡන්ද හිමි නාමලේඛනය - වර්ෂය 5",
      labelEn: "Electoral Register Year 5",
      type: "number",
      required: false,
    },
    {
      key: "electoralDistrict5",
      labelSi: "ඡන්ද ප්‍රදේශය 5",
      labelEn: "Electoral District 5",
      type: "text",
      required: false,
    },
    {
      key: "electoralGnDivision5",
      labelSi: "ග්‍රාම නිලධාරි වසම හා අංකය 5",
      labelEn: "GN Division and Number 5",
      type: "text",
      required: false,
    },
    {
      key: "electoralPollingDivision5",
      labelSi: "ඡන්ද කොට්ඨාශය 5",
      labelEn: "Polling Division 5",
      type: "text",
      required: false,
    },
    {
      key: "electoralVillageStreetEstate5",
      labelSi: "ගම / වීදිය / වත්ත 5",
      labelEn: "Village / Street / Estate 5",
      type: "text",
      required: false,
    },
    {
      key: "electoralHouseholdNumber5",
      labelSi: "ගෘහ / පදිංචි අංකය 5",
      labelEn: "Household / Residence Number 5",
      type: "text",
      required: false,
    },
    {
      key: "electoralRegisteredNames5",
      labelSi: "ඡන්ද හිමි නාමලේඛනයේ නම් 5",
      labelEn: "Names in Electoral Register 5",
      type: "text",
      required: false,
    },
    {
      key: "sibling1Name",
      labelSi: "සහෝදර/සහෝදරිය 1 - නම",
      labelEn: "Sibling 1 Name",
      type: "text",
      required: false,
    },
    {
      key: "sibling1AdmissionNumber",
      labelSi: "සහෝදර/සහෝදරිය 1 - ඇතුළත් වීමේ අංකය",
      labelEn: "Sibling 1 Admission Number",
      type: "text",
      required: false,
    },
    {
      key: "sibling1CurrentGrade",
      labelSi: "සහෝදර/සහෝදරිය 1 - වර්තමාන ශ්‍රේණිය",
      labelEn: "Sibling 1 Current Grade",
      type: "text",
      required: false,
    },
    {
      key: "sibling1YearsInSchool",
      labelSi: "සහෝදර/සහෝදරිය 1 - පාසලේ වසර ගණන",
      labelEn: "Sibling 1 Years in School",
      type: "number",
      required: false,
    },
    {
      key: "sibling2Name",
      labelSi: "සහෝදර/සහෝදරිය 2 - නම",
      labelEn: "Sibling 2 Name",
      type: "text",
      required: false,
    },
    {
      key: "sibling2AdmissionNumber",
      labelSi: "සහෝදර/සහෝදරිය 2 - ඇතුළත් වීමේ අංකය",
      labelEn: "Sibling 2 Admission Number",
      type: "text",
      required: false,
    },
    {
      key: "sibling2CurrentGrade",
      labelSi: "සහෝදර/සහෝදරිය 2 - වර්තමාන ශ්‍රේණිය",
      labelEn: "Sibling 2 Current Grade",
      type: "text",
      required: false,
    },
    {
      key: "sibling2YearsInSchool",
      labelSi: "සහෝදර/සහෝදරිය 2 - පාසලේ වසර ගණන",
      labelEn: "Sibling 2 Years in School",
      type: "number",
      required: false,
    },
    {
      key: "sibling3Name",
      labelSi: "සහෝදර/සහෝදරිය 3 - නම",
      labelEn: "Sibling 3 Name",
      type: "text",
      required: false,
    },
    {
      key: "sibling3AdmissionNumber",
      labelSi: "සහෝදර/සහෝදරිය 3 - ඇතුළත් වීමේ අංකය",
      labelEn: "Sibling 3 Admission Number",
      type: "text",
      required: false,
    },
    {
      key: "sibling3CurrentGrade",
      labelSi: "සහෝදර/සහෝදරිය 3 - වර්තමාන ශ්‍රේණිය",
      labelEn: "Sibling 3 Current Grade",
      type: "text",
      required: false,
    },
    {
      key: "sibling3YearsInSchool",
      labelSi: "සහෝදර/සහෝදරිය 3 - පාසලේ වසර ගණන",
      labelEn: "Sibling 3 Years in School",
      type: "number",
      required: false,
    },
    {
      key: "sibling4Name",
      labelSi: "සහෝදර/සහෝදරිය 4 - නම",
      labelEn: "Sibling 4 Name",
      type: "text",
      required: false,
    },
    {
      key: "sibling4AdmissionNumber",
      labelSi: "සහෝදර/සහෝදරිය 4 - ඇතුළත් වීමේ අංකය",
      labelEn: "Sibling 4 Admission Number",
      type: "text",
      required: false,
    },
    {
      key: "sibling4CurrentGrade",
      labelSi: "සහෝදර/සහෝදරිය 4 - වර්තමාන ශ්‍රේණිය",
      labelEn: "Sibling 4 Current Grade",
      type: "text",
      required: false,
    },
    {
      key: "sibling4YearsInSchool",
      labelSi: "සහෝදර/සහෝදරිය 4 - පාසලේ වසර ගණන",
      labelEn: "Sibling 4 Years in School",
      type: "number",
      required: false,
    },
    {
      key: "unusedLeaveDays2022",
      labelSi: "2022 - ලබා නොගත් නිවාඩු දින",
      labelEn: "Unused Leave Days 2022",
      type: "number",
      required: false,
    },
    {
      key: "unusedLeaveDays2021",
      labelSi: "2021 - ලබා නොගත් නිවාඩු දින",
      labelEn: "Unused Leave Days 2021",
      type: "number",
      required: false,
    },
    {
      key: "unusedLeaveDays2020",
      labelSi: "2020 - ලබා නොගත් නිවාඩු දින",
      labelEn: "Unused Leave Days 2020",
      type: "number",
      required: false,
    },
    {
      key: "unusedLeaveDays2019",
      labelSi: "2019 - ලබා නොගත් නිවාඩු දින",
      labelEn: "Unused Leave Days 2019",
      type: "number",
      required: false,
    },
    {
      key: "unusedLeaveDays2018",
      labelSi: "2018 - ලබා නොගත් නිවාඩු දින",
      labelEn: "Unused Leave Days 2018",
      type: "number",
      required: false,
    },
    {
      key: "transferServicePlace2022",
      labelSi: "2022 - සේවා ස්ථානය",
      labelEn: "Service Place 2022",
      type: "text",
      required: false,
    },
    {
      key: "transferServiceDistrict2022",
      labelSi: "2022 - සේවා දිස්ත්‍රික්කය",
      labelEn: "Service District 2022",
      type: "text",
      required: false,
    },
    {
      key: "transferUnusedLeaveDays2022",
      labelSi: "2022 - ස්ථාන මාරු කාණ්ඩයට ලබා නොගත් නිවාඩු දින",
      labelEn: "Transfer Category Unused Leave Days 2022",
      type: "number",
      required: false,
    },
    {
      key: "transferServicePlace2021",
      labelSi: "2021 - සේවා ස්ථානය",
      labelEn: "Service Place 2021",
      type: "text",
      required: false,
    },
    {
      key: "transferServiceDistrict2021",
      labelSi: "2021 - සේවා දිස්ත්‍රික්කය",
      labelEn: "Service District 2021",
      type: "text",
      required: false,
    },
    {
      key: "transferUnusedLeaveDays2021",
      labelSi: "2021 - ස්ථාන මාරු කාණ්ඩයට ලබා නොගත් නිවාඩු දින",
      labelEn: "Transfer Category Unused Leave Days 2021",
      type: "number",
      required: false,
    },
    {
      key: "transferServicePlace2020",
      labelSi: "2020 - සේවා ස්ථානය",
      labelEn: "Service Place 2020",
      type: "text",
      required: false,
    },
    {
      key: "transferServiceDistrict2020",
      labelSi: "2020 - සේවා දිස්ත්‍රික්කය",
      labelEn: "Service District 2020",
      type: "text",
      required: false,
    },
    {
      key: "transferUnusedLeaveDays2020",
      labelSi: "2020 - ස්ථාන මාරු කාණ්ඩයට ලබා නොගත් නිවාඩු දින",
      labelEn: "Transfer Category Unused Leave Days 2020",
      type: "number",
      required: false,
    },
    {
      key: "transferServicePlace2019",
      labelSi: "2019 - සේවා ස්ථානය",
      labelEn: "Service Place 2019",
      type: "text",
      required: false,
    },
    {
      key: "transferServiceDistrict2019",
      labelSi: "2019 - සේවා දිස්ත්‍රික්කය",
      labelEn: "Service District 2019",
      type: "text",
      required: false,
    },
    {
      key: "transferUnusedLeaveDays2019",
      labelSi: "2019 - ස්ථාන මාරු කාණ්ඩයට ලබා නොගත් නිවාඩු දින",
      labelEn: "Transfer Category Unused Leave Days 2019",
      type: "number",
      required: false,
    },
    {
      key: "transferServicePlace2018",
      labelSi: "2018 - සේවා ස්ථානය",
      labelEn: "Service Place 2018",
      type: "text",
      required: false,
    },
    {
      key: "transferServiceDistrict2018",
      labelSi: "2018 - සේවා දිස්ත්‍රික්කය",
      labelEn: "Service District 2018",
      type: "text",
      required: false,
    },
    {
      key: "transferUnusedLeaveDays2018",
      labelSi: "2018 - ස්ථාන මාරු කාණ්ඩයට ලබා නොගත් නිවාඩු දින",
      labelEn: "Transfer Category Unused Leave Days 2018",
      type: "number",
      required: false,
    },

    { key: "applicationDate", labelSi: "අයදුම්පතේ දිනය", labelEn: "Application Date", type: "date", required: true },

    { key: "criteria711PrimaryResidenceDocument", labelSi: "7.1.1 පදිංචිය තහවුරු කරන ප්‍රධාන ලේඛනය", labelEn: "7.1.1 Primary Residence Document", type: "text", required: false },
    { key: "criteria712AdditionalResidenceDocuments", labelSi: "7.1.2 පදිංචිය තහවුරු කරන අතිරේක ලේඛන", labelEn: "7.1.2 Additional Residence Documents", type: "text", required: false },
    { key: "criteria713ElectoralRegistrationDetails", labelSi: "7.1.3 ඡන්ද හිමි ලියාපදිංචි විස්තර", labelEn: "7.1.3 Electoral Registration Details", type: "text", required: false },
    { key: "criteria714CloserSchoolCount", labelSi: "7.1.4 ආසන්න වෙනත් පාසල් සංඛ්‍යාව", labelEn: "7.1.4 Number of Closer Schools", type: "number", required: false },

    { key: "criteria721PastPupilDetails", labelSi: "7.2.1 ආදි ශිෂ්‍ය විස්තර", labelEn: "7.2.1 Past Pupil Details", type: "text", required: false },
    { key: "criteria722AcademicAchievements", labelSi: "7.2.2 අධ්‍යාපන ජයග්‍රහණ", labelEn: "7.2.2 Academic Achievements", type: "text", required: false },
    { key: "criteria723CoCurricularAchievements", labelSi: "7.2.3 විෂය සමගාමී ජයග්‍රහණ", labelEn: "7.2.3 Co-curricular Achievements", type: "text", required: false },
    { key: "criteria724PastPupilContribution", labelSi: "7.2.4 ආදි ශිෂ්‍ය සංගමය / පාසල් දායකත්වය", labelEn: "7.2.4 Past Pupil Contribution", type: "text", required: false },

    { key: "criteria732SiblingContribution", labelSi: "7.3.2 සහෝදර දායකත්වය / ජයග්‍රහණ", labelEn: "7.3.2 Sibling Contribution / Achievements", type: "text", required: false },
    { key: "criteria733PrimaryResidenceDocument", labelSi: "7.3.3 පදිංචිය තහවුරු කරන ලේඛනය", labelEn: "7.3.3 Residence Document", type: "text", required: false },
    { key: "criteria734ElectoralRegistrationDetails", labelSi: "7.3.4 ඡන්ද හිමි ලියාපදිංචි විස්තර", labelEn: "7.3.4 Electoral Registration Details", type: "text", required: false },
    { key: "criteria735CloserSchoolCount", labelSi: "7.3.5 ආසන්න වෙනත් පාසල් සංඛ්‍යාව", labelEn: "7.3.5 Number of Closer Schools", type: "number", required: false },

    { key: "criteria741EducationServicePeriod", labelSi: "7.4.1 අධ්‍යාපන සේවා කාලය", labelEn: "7.4.1 Education Service Period", type: "text", required: false },
    { key: "criteria742PreviousServicePlace", labelSi: "7.4.2 පෙර සේවා ස්ථානය", labelEn: "7.4.2 Previous Service Place", type: "text", required: false },
    { key: "criteria743CurrentServiceDetails", labelSi: "7.4.3 වර්තමාන සේවා විස්තර", labelEn: "7.4.3 Current Service Details", type: "text", required: false },
    { key: "criteria745ServiceAtRequestedSchool", labelSi: "7.4.5 ඉල්ලුම් කරන පාසලේ සේවා කාලය", labelEn: "7.4.5 Service at Requested School", type: "text", required: false },
    { key: "criteria746WorkplaceToSchoolDistanceKm", labelSi: "7.4.6 සේවා ස්ථානයේ සිට පාසලට දුර", labelEn: "7.4.6 Workplace to School Distance", type: "number", required: false },
    { key: "criteria747PrimaryResidenceDocument", labelSi: "7.4.7 පදිංචිය තහවුරු කරන ලේඛනය", labelEn: "7.4.7 Residence Document", type: "text", required: false },
    { key: "criteria748ResidenceToSchoolDistanceKm", labelSi: "7.4.8 පදිංචි ස්ථානයේ සිට පාසලට දුර", labelEn: "7.4.8 Residence to School Distance", type: "number", required: false },

    { key: "criteria751TransferArrivalDate", labelSi: "7.5.1 ස්ථාන මාරුවෙන් පැමිණි දිනය", labelEn: "7.5.1 Transfer Arrival Date", type: "date", required: false },
    { key: "criteria752PreviousWorkplaceDetails", labelSi: "7.5.2 පෙර සේවා ස්ථානයේ විස්තර", labelEn: "7.5.2 Previous Workplace Details", type: "text", required: false },
    { key: "criteria753PreviousResidenceAddress", labelSi: "7.5.3 පෙර පදිංචි ලිපිනය", labelEn: "7.5.3 Previous Residence Address", type: "address", required: false },
    { key: "criteria754PreviousChildSchool", labelSi: "7.5.4 දරුවා පෙර ඉගෙනුම ලැබූ පාසල", labelEn: "7.5.4 Child Previous School", type: "text", required: false },
    { key: "criteria755NewResidenceAddress", labelSi: "7.5.5 නව පදිංචි ලිපිනය", labelEn: "7.5.5 New Residence Address", type: "address", required: false },
    { key: "criteria756PreviousDistance", labelSi: "7.5.6 පෙර ස්ථානයේ සිට දුර", labelEn: "7.5.6 Previous Distance", type: "text", required: false },
    { key: "criteria757NewWorkplaceToSchoolDistanceKm", labelSi: "7.5.7 නව සේවා ස්ථානයේ සිට පාසලට දුර", labelEn: "7.5.7 New Workplace to School Distance", type: "number", required: false },
    { key: "criteria759CloserSchoolCount", labelSi: "7.5.9 ආසන්න වෙනත් පාසල් සංඛ්‍යාව", labelEn: "7.5.9 Number of Closer Schools", type: "number", required: false },
    { key: "criteria7510SpecialServicePeriod", labelSi: "7.5.10 විශේෂ රාජ්‍ය සේවා කාලය", labelEn: "7.5.10 Special Public Service Period", type: "text", required: false },

    { key: "foreignResidenceCountry", labelSi: "7.6.1 විදේශගතව සිටි රට", labelEn: "7.6.1 Country of Foreign Residence", type: "text", required: false },
    { key: "foreignResidencePeriod", labelSi: "7.6.2 විදේශගතව සිටි කාල සීමාව", labelEn: "7.6.2 Period of Foreign Residence", type: "text", required: false },
    { key: "reasonForForeignResidence", labelSi: "7.6.3 විදේශගත වූ හේතුව", labelEn: "7.6.3 Reason for Foreign Residence", type: "text", required: false },
    { key: "criteria764CloserSchoolCount", labelSi: "7.6.4 ආසන්න වෙනත් පාසල් සංඛ්‍යාව", labelEn: "7.6.4 Number of Closer Schools", type: "number", required: false },

    { key: "declarationDate", labelSi: "ප්‍රකාශයේ දිනය", labelEn: "Declaration Date", type: "date", required: true },
  ],
};
