import { EDUCATION_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const railwayStationMasterGradeIIIApplicationFormDefinition: DataCollectionForm = {
  id: "railway-station-master-grade-iii-application-2025",
  nameSi: "දුම්රිය ස්ථානාධිපති III ශ්‍රේණියට බඳවා ගැනීමේ විවෘත තරග විභාග අයදුම්පත - 2025",
  nameEn: "Station Master Grade III Open Competitive Examination Application - 2025",
  documentPath:
    "/forms/employment/railway-station-master-grade-iii-application-2025.pdf",
  category: EDUCATION_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds to a {{fieldKey}} placeholder or a choice-control region in the static OCR/layout annotation template.",
    "When applying generated values, replace only matching placeholders or resolve the corresponding printed choice. Do not modify fixed OCR text, bounding boxes, labels, reading order, page numbers, tables, headings, office-use-only fields, printer marks, or scan watermarks.",
    "Generate one internally consistent synthetic applicant for the Sri Lanka Railway Department Station Master Grade III open competitive examination - 2025.",
    "fullNameSinhalaOrTamil and fullNameEnglishCapital must refer to the same applicant. The English name must use uppercase Latin letters.",
    "permanentAddressSinhalaOrTamil and permanentAddressEnglish must describe the same address in the respective scripts/languages.",
    "mobilePhone and officePhone must be plausible synthetic Sri Lankan telephone numbers. officePhone may be an empty string if not applicable.",
    "nicNumber must be a plausible synthetic Sri Lankan NIC number.",
    "examMediumCode must be one of the printed codes: 2 for Sinhala or 3 for Tamil.",
    "citizenshipBasisCode must be one of the printed codes: 1 for citizenship by descent or 2 for citizenship by registration.",
    "examCityPreference1 and examCityPreference2 must be plausible exam-city preferences and should not be identical.",
    "sexCode must use the exact printed code: 1 for female or 0 for male.",
    "ethnicityCode must use one of the printed codes: Sinhala=1, Sri Lankan Tamil=2, Indian Tamil=3, Muslim=4, Burgher=5, Malay=6.",
    "gnDivisionName, gnDivisionNumber, divisionalSecretariat, district, and the permanent address must be geographically consistent.",
    "birthYear, birthMonth, and birthDay must form a valid date of birth.",
    "ageYearsAt20250714, ageMonthsAt20250714, and ageDaysAt20250714 must exactly match the applicant's date of birth as at 2025-07-14.",
    "currentEmployerOrDepartment is optional. Return an empty string if the applicant is not currently employed.",
    "olExamIndexNumber and olExamYear must be plausible and chronologically consistent with the applicant's age.",
    "Populate O/L rows consecutively. Each populated olSubjectNName must have a corresponding olSubjectNGrade; return empty strings for unused rows.",
    "alExamIndexNumber and alExamYear should be populated only when applicable and must be chronologically consistent with the applicant's age.",
    "Populate A/L rows consecutively. Each populated alSubjectNName must have a corresponding alSubjectNGrade; return empty strings for unused rows.",
    "courtConvictionStatus must resolve the printed Yes/No choice. Use a concise value equivalent to ඔව් or නැත.",
    "examFeePaymentDate must use YYYY-MM-DD. examFeePostOffice and examFeeReceiptNumber must describe one plausible synthetic examination-fee payment of Rs. 1200.",
    "attestedApplicantName must exactly match the applicant name used elsewhere in the form.",
    "signatureAttestationDate and signatureAttestorDate must use YYYY-MM-DD and must be chronologically plausible.",
    "signatureAttestorFullName, signatureAttestorDesignation, and signatureAttestorAddress must describe one plausible synthetic person authorized to certify the applicant's signature. Do not use a real identifiable public official.",
    "The departmental/institutional-head certification is applicable only if the applicant is currently serving in a department or institution. If it is not applicable, return empty strings for departmentCertificationApplicantName, currentDepartmentOrInstitution, departmentServiceFromDate, departmentServiceToDate, departmentServicePeriod, departmentHeadCertificationDate, departmentHeadFullName, departmentHeadDesignation, and departmentHeadAddress.",
    "If the departmental/institutional-head certification is applicable, departmentCertificationApplicantName must match the applicant, currentDepartmentOrInstitution must be consistent with currentEmployerOrDepartment, and the service dates/period must be mutually consistent.",
    "All dates must use YYYY-MM-DD unless a field is explicitly a numeric year/month/day component.",
    "Keep generated values concise enough to fit naturally inside their assigned boxes and dotted lines.",
    "Use only synthetic names, identifiers, addresses, telephone numbers, examination records, employment information, receipt numbers, and certifier details. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys defined in the fields array. Do not invent additional ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, office-use-only values, signatures, stamps, printer marks, or scan watermarks. Those are already represented in the static annotation template.",
    "applicantSignature, signatureAttestorSignature, signatureAttestorOfficialStamp, departmentHeadSignature, and departmentHeadOfficialStamp are image-style annotation regions and should not be returned as ordinary text values unless the rendering pipeline explicitly supports synthetic image assets."
  ],

  fields: [
    // ------------------------------------------------------------
    // Top coded selections / examination city preferences
    // ------------------------------------------------------------
    {
      key: "examMediumCode",
      labelSi: "විභාගය සඳහා ඉල්ලුම් කරන මාධ්‍ය කේතය",
      labelEn: "Examination Medium Code",
      type: "number",
      required: true,
      helpTextSi: "සිංහල = 2 / දෙමළ = 3.",
    },
    {
      key: "citizenshipBasisCode",
      labelSi: "පුරවැසිභාවයේ පදනම",
      labelEn: "Citizenship Basis Code",
      type: "number",
      required: true,
      helpTextSi: "පරම්පරාවෙන් = 1 / ලියාපදිංචියෙන් = 2.",
    },
    {
      key: "examCityPreference1",
      labelSi: "විභාග නගරය - පළමු කැමැත්ත",
      labelEn: "Examination City - First Preference",
      type: "text",
      required: true,
    },
    {
      key: "examCityPreference2",
      labelSi: "විභාග නගරය - දෙවන කැමැත්ත",
      labelEn: "Examination City - Second Preference",
      type: "text",
      required: true,
    },

    // ------------------------------------------------------------
    // Applicant identity/contact
    // ------------------------------------------------------------
    {
      key: "fullNameSinhalaOrTamil",
      labelSi: "සම්පූර්ණ නම - සිංහලෙන් / දෙමළෙන්",
      labelEn: "Full Name - Sinhala / Tamil",
      type: "text",
      required: true,
    },
    {
      key: "fullNameEnglishCapital",
      labelSi: "සම්පූර්ණ නම - ඉංග්‍රීසි කැපිටල් අකුරින්",
      labelEn: "Full Name - English Capital Letters",
      type: "text",
      required: true,
    },
    {
      key: "permanentAddressSinhalaOrTamil",
      labelSi: "ස්ථිර ලිපිනය - සිංහලෙන් / දෙමළෙන්",
      labelEn: "Permanent Address - Sinhala / Tamil",
      type: "address",
      required: true,
    },
    {
      key: "permanentAddressEnglish",
      labelSi: "ස්ථිර ලිපිනය - ඉංග්‍රීසියෙන්",
      labelEn: "Permanent Address - English",
      type: "address",
      required: true,
    },
    {
      key: "mobilePhone",
      labelSi: "ජංගම දුරකථන අංකය",
      labelEn: "Mobile Phone Number",
      type: "phone",
      required: true,
    },
    {
      key: "officePhone",
      labelSi: "කාර්යාලීය දුරකථන අංකය",
      labelEn: "Office Phone Number",
      type: "phone",
      required: false,
    },
    {
      key: "nicNumber",
      labelSi: "ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "National Identity Card Number",
      type: "nic",
      required: true,
    },
    {
      key: "sexCode",
      labelSi: "ස්ත්‍රී / පුරුෂ භාවය කේතය",
      labelEn: "Sex Code",
      type: "number",
      required: true,
      helpTextSi: "ස්ත්‍රී = 1 / පුරුෂ = 0.",
    },

    // ------------------------------------------------------------
    // Residence / ethnicity / DOB
    // ------------------------------------------------------------
    {
      key: "ethnicityCode",
      labelSi: "ජන වර්ග කේතය",
      labelEn: "Ethnicity Code",
      type: "number",
      required: true,
    },
    {
      key: "gnDivisionName",
      labelSi: "ග්‍රාම නිලධාරි කොට්ඨාසය",
      labelEn: "GN Division",
      type: "text",
      required: true,
    },
    {
      key: "gnDivisionNumber",
      labelSi: "ග්‍රාම නිලධාරි වසම් අංකය",
      labelEn: "GN Division Number",
      type: "text",
      required: true,
    },
    {
      key: "divisionalSecretariat",
      labelSi: "ප්‍රාදේශීය ලේකම් කොට්ඨාසය",
      labelEn: "Divisional Secretariat",
      type: "text",
      required: true,
    },
    {
      key: "district",
      labelSi: "දිස්ත්‍රික්කය",
      labelEn: "District",
      type: "text",
      required: true,
    },
    {
      key: "birthYear",
      labelSi: "උපන් වර්ෂය",
      labelEn: "Birth Year",
      type: "number",
      required: true,
    },
    {
      key: "birthMonth",
      labelSi: "උපන් මාසය",
      labelEn: "Birth Month",
      type: "number",
      required: true,
    },
    {
      key: "birthDay",
      labelSi: "උපන් දිනය",
      labelEn: "Birth Day",
      type: "number",
      required: true,
    },
    {
      key: "ageYearsAt20250714",
      labelSi: "2025-07-14 දිනට වයස - අවුරුදු",
      labelEn: "Age at 2025-07-14 - Years",
      type: "number",
      required: true,
    },
    {
      key: "ageMonthsAt20250714",
      labelSi: "2025-07-14 දිනට වයස - මාස",
      labelEn: "Age at 2025-07-14 - Months",
      type: "number",
      required: true,
    },
    {
      key: "ageDaysAt20250714",
      labelSi: "2025-07-14 දිනට වයස - දින",
      labelEn: "Age at 2025-07-14 - Days",
      type: "number",
      required: true,
    },
    {
      key: "currentEmployerOrDepartment",
      labelSi: "දැනට සේවය කරන ආයතනය / දෙපාර්තමේන්තුව",
      labelEn: "Current Employer / Department",
      type: "text",
      required: false,
    },

    // ------------------------------------------------------------
    // O/L
    // ------------------------------------------------------------
    {
      key: "olExamIndexNumber",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විභාග අංකය",
      labelEn: "O/L Examination Index Number",
      type: "text",
      required: true,
    },
    {
      key: "olExamYear",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ වර්ෂය",
      labelEn: "O/L Examination Year",
      type: "number",
      required: true,
    },

    {
      key: "olSubject1Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 1",
      labelEn: "O/L Subject 1",
      type: "text",
      required: false,
    },
    {
      key: "olSubject1Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 1 ශ්‍රේණිය",
      labelEn: "O/L Subject 1 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject2Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 2",
      labelEn: "O/L Subject 2",
      type: "text",
      required: false,
    },
    {
      key: "olSubject2Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 2 ශ්‍රේණිය",
      labelEn: "O/L Subject 2 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject3Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 3",
      labelEn: "O/L Subject 3",
      type: "text",
      required: false,
    },
    {
      key: "olSubject3Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 3 ශ්‍රේණිය",
      labelEn: "O/L Subject 3 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject4Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 4",
      labelEn: "O/L Subject 4",
      type: "text",
      required: false,
    },
    {
      key: "olSubject4Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 4 ශ්‍රේණිය",
      labelEn: "O/L Subject 4 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject5Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 5",
      labelEn: "O/L Subject 5",
      type: "text",
      required: false,
    },
    {
      key: "olSubject5Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 5 ශ්‍රේණිය",
      labelEn: "O/L Subject 5 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject6Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 6",
      labelEn: "O/L Subject 6",
      type: "text",
      required: false,
    },
    {
      key: "olSubject6Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 6 ශ්‍රේණිය",
      labelEn: "O/L Subject 6 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject7Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 7",
      labelEn: "O/L Subject 7",
      type: "text",
      required: false,
    },
    {
      key: "olSubject7Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 7 ශ්‍රේණිය",
      labelEn: "O/L Subject 7 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject8Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 8",
      labelEn: "O/L Subject 8",
      type: "text",
      required: false,
    },
    {
      key: "olSubject8Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 8 ශ්‍රේණිය",
      labelEn: "O/L Subject 8 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject9Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 9",
      labelEn: "O/L Subject 9",
      type: "text",
      required: false,
    },
    {
      key: "olSubject9Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 9 ශ්‍රේණිය",
      labelEn: "O/L Subject 9 Grade",
      type: "text",
      required: false,
    },
    {
      key: "olSubject10Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 10",
      labelEn: "O/L Subject 10",
      type: "text",
      required: false,
    },
    {
      key: "olSubject10Grade",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 10 ශ්‍රේණිය",
      labelEn: "O/L Subject 10 Grade",
      type: "text",
      required: false,
    },

    // ------------------------------------------------------------
    // A/L
    // ------------------------------------------------------------
    {
      key: "alExamIndexNumber",
      labelSi: "අ.පො.ස. උසස් පෙළ විභාග අංකය",
      labelEn: "A/L Examination Index Number",
      type: "text",
      required: false,
    },
    {
      key: "alExamYear",
      labelSi: "අ.පො.ස. උසස් පෙළ වර්ෂය",
      labelEn: "A/L Examination Year",
      type: "number",
      required: false,
    },

    {
      key: "alSubject1Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 1",
      labelEn: "A/L Subject 1",
      type: "text",
      required: false,
    },
    {
      key: "alSubject1Grade",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 1 ශ්‍රේණිය",
      labelEn: "A/L Subject 1 Grade",
      type: "text",
      required: false,
    },
    {
      key: "alSubject2Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 2",
      labelEn: "A/L Subject 2",
      type: "text",
      required: false,
    },
    {
      key: "alSubject2Grade",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 2 ශ්‍රේණිය",
      labelEn: "A/L Subject 2 Grade",
      type: "text",
      required: false,
    },
    {
      key: "alSubject3Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 3",
      labelEn: "A/L Subject 3",
      type: "text",
      required: false,
    },
    {
      key: "alSubject3Grade",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 3 ශ්‍රේණිය",
      labelEn: "A/L Subject 3 Grade",
      type: "text",
      required: false,
    },
    {
      key: "alSubject4Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 4",
      labelEn: "A/L Subject 4",
      type: "text",
      required: false,
    },
    {
      key: "alSubject4Grade",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 4 ශ්‍රේණිය",
      labelEn: "A/L Subject 4 Grade",
      type: "text",
      required: false,
    },
    {
      key: "alSubject5Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 5",
      labelEn: "A/L Subject 5",
      type: "text",
      required: false,
    },
    {
      key: "alSubject5Grade",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 5 ශ්‍රේණිය",
      labelEn: "A/L Subject 5 Grade",
      type: "text",
      required: false,
    },

    {
      key: "courtConvictionStatus",
      labelSi: "උසාවියකින් වරදකරු කරනු ලැබ තිබේද",
      labelEn: "Previously Convicted by a Court",
      type: "text",
      required: true,
      helpTextSi: "ඔව් / නැත ලෙස සඳහන් කරන්න.",
    },

    // ------------------------------------------------------------
    // Applicant certification / exam-fee payment
    // ------------------------------------------------------------
    {
      key: "examFeePaymentDate",
      labelSi: "විභාග ගාස්තුව ගෙවූ දිනය",
      labelEn: "Examination Fee Payment Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "examFeePostOffice",
      labelSi: "විභාග ගාස්තුව ගෙවූ තැපැල් කාර්යාලය",
      labelEn: "Post Office Used for Examination Fee Payment",
      type: "text",
      required: true,
    },
    {
      key: "examFeeReceiptNumber",
      labelSi: "විභාග ගාස්තු ලදුපත් අංකය",
      labelEn: "Examination Fee Receipt Number",
      type: "text",
      required: true,
    },

    // ------------------------------------------------------------
    // Signature attestation
    // ------------------------------------------------------------
    {
      key: "attestedApplicantName",
      labelSi: "අත්සන සහතික කිරීමේ සඳහන් අයදුම්කරුගේ නම",
      labelEn: "Applicant Name in Signature Attestation",
      type: "text",
      required: true,
    },
    {
      key: "signatureAttestationDate",
      labelSi: "අයදුම්කරු අත්සන් කළ දිනය",
      labelEn: "Applicant Signature Attestation Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "signatureAttestorDate",
      labelSi: "අත්සන සහතික කරන අයගේ දිනය",
      labelEn: "Signature Certifier Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "signatureAttestorFullName",
      labelSi: "අත්සන සහතික කරන අයගේ සම්පූර්ණ නම",
      labelEn: "Signature Certifier Full Name",
      type: "text",
      required: true,
    },
    {
      key: "signatureAttestorDesignation",
      labelSi: "අත්සන සහතික කරන අයගේ තනතුර",
      labelEn: "Signature Certifier Designation",
      type: "text",
      required: true,
    },
    {
      key: "signatureAttestorAddress",
      labelSi: "අත්සන සහතික කරන අයගේ ලිපිනය",
      labelEn: "Signature Certifier Address",
      type: "address",
      required: true,
    },

    // ------------------------------------------------------------
    // Department / institution head certification - if applicable
    // ------------------------------------------------------------
    {
      key: "departmentCertificationApplicantName",
      labelSi: "දෙපාර්තමේන්තු / ආයතන සහතිකයේ අයදුම්කරුගේ නම",
      labelEn: "Applicant Name in Department Certification",
      type: "text",
      required: false,
    },
    {
      key: "currentDepartmentOrInstitution",
      labelSi: "දෙපාර්තමේන්තුව / ආයතනය",
      labelEn: "Department / Institution",
      type: "text",
      required: false,
    },
    {
      key: "departmentServiceFromDate",
      labelSi: "සේවා ආරම්භ දිනය",
      labelEn: "Department Service From Date",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "departmentServiceToDate",
      labelSi: "සේවා අවසන් / වර්තමාන දිනය",
      labelEn: "Department Service To Date",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "departmentServicePeriod",
      labelSi: "සේවා කාලය",
      labelEn: "Department Service Period",
      type: "text",
      required: false,
    },
    {
      key: "departmentHeadCertificationDate",
      labelSi: "දෙපාර්තමේන්තු / ආයතන ප්‍රධානියා සහතික කළ දිනය",
      labelEn: "Department Head Certification Date",
      type: "date",
      required: false,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
    {
      key: "departmentHeadFullName",
      labelSi: "සහතික කරන දෙපාර්තමේන්තු / ආයතන ප්‍රධානියාගේ සම්පූර්ණ නම",
      labelEn: "Department / Institution Head Full Name",
      type: "text",
      required: false,
    },
    {
      key: "departmentHeadDesignation",
      labelSi: "දෙපාර්තමේන්තු / ආයතන ප්‍රධානියාගේ තනතුර",
      labelEn: "Department / Institution Head Designation",
      type: "text",
      required: false,
    },
    {
      key: "departmentHeadAddress",
      labelSi: "දෙපාර්තමේන්තු / ආයතන ප්‍රධානියාගේ ලිපිනය",
      labelEn: "Department / Institution Head Address",
      type: "address",
      required: false,
    },
  ],
};
