import { EDUCATION_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const schoolAdmissionGrade2To11FormDefinition: DataCollectionForm = {
  id: "school-admission-grade-2-11",
  nameSi: "2 ශ්‍රේණියේ සිට 11 ශ්‍රේණිය දක්වා පාසල් ඇතුළත් කිරීමේ අයදුම්පත",
  nameEn: "School Admission Application - Grades 2 to 11",
  documentPath: "/forms/education/school-admission-grade-2-11.pdf",
  category: EDUCATION_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated value corresponds to a {{fieldKey}} placeholder in the static OCR/layout annotation template.",
    "When applying values, replace only matching placeholders. Do not modify fixed OCR text, bounding boxes, labels, reading order, page numbers, table structure, office-use-only marks columns, printer marks, or scan watermarks.",
    "Generate one internally consistent synthetic Sri Lankan school-admission scenario.",
    "This form is intended for admission to Grades 2-11 excluding Grades 5 and 6. gradeAppliedFor must therefore be one of 2, 3, 4, 7, 8, 9, 10, or 11.",
    "applicationYear must be a plausible four-digit year and must be reused wherever the year appears in the title and age-reference line.",
    "schoolName and the preferred-school list must be plausible Sri Lankan schools. Avoid using real individual student/parent identities.",
    "admissionCategory must identify the category that justifies the application. Populate only the criteria section on pages 2-3 that is relevant to that category; return empty strings for irrelevant criteria fields.",
    "studentFullName, studentNameWithInitialsSinhalaTamil, and studentNameWithInitialsEnglish must refer to the same child.",
    "studentGender, studentReligion, mediumOfStudy, birthYear, birthMonth, birthDay, ageYearsAtJan31, ageMonthsAtJan31, and ageDaysAtJan31 must be mutually consistent.",
    "ageYearsAtJan31, ageMonthsAtJan31, and ageDaysAtJan31 must represent the student's exact age on January 31 of applicationYear.",
    "currentSchoolAndGrade must be plausible and consistent with gradeAppliedFor.",
    "All applicant details must describe one parent or legal guardian. applicantPermanentAddress, applicantDistrict, applicantDivisionalSecretariat, applicantGnDivision, applicantGnDivisionNumber, and currentResidenceAddress must be geographically consistent.",
    "If there is no previous residence relevant to the application, previousResidenceAddress must be an empty string.",
    "Preferred-school rows must be populated consecutively from preferredSchool1. Each populated row should contain a school name and a plausible type such as ජාතික or පළාත්. Return empty strings for unused rows.",
    "For transfer-related sections 4.1 and 4.4, workplace names, dates, elapsed periods, reasons and distances must describe one internally consistent transfer scenario. Populate only the applicable transfer section.",
    "For section 4.2, return-to-Sri-Lanka date, foreign-stay period, reason for foreign residence and residence-to-school distance must form one plausible scenario.",
    "For section 4.3, reason for residence change, arrival date, previous/new addresses and distances must be internally consistent.",
    "For section 4.5, scholarship examination year, district and marks must be plausible. This category is relevant only to Grades 7-11.",
    "For section 4.6, occupation/designation, workplace, service periods and distances must describe one plausible staff-category scenario.",
    "criteria47FinalTermTotalMarks and criteria47FinalTermAverageMarks must be mutually plausible and refer to the student's most recent term examination.",
    "Sports, aesthetic, innovation, co/extra-curricular and leadership rows on page 4 are optional. Populate each table consecutively from row 1 and return empty strings for all unused rows.",
    "Achievement levels should use concise values compatible with the printed form, for example පාසල්, කොට්ඨාශ, කලාප, පළාත්, ජාතික or අන්තර්ජාතික.",
    "declarationDate must use YYYY-MM-DD and must be chronologically plausible.",
    "Keep all generated values concise enough to fit naturally within the corresponding bounding boxes.",
    "Use only synthetic names, NICs, phone numbers, addresses, school data and supporting details. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys in the fields array. Do not invent extra ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, office-use-only marks, signatures, printer marks or scan watermarks. Those are already stored in the static annotation template.",
    "parentGuardianSignature is an image-style Signature region and should not be returned as an ordinary Gemini text field unless the rendering pipeline explicitly supports synthetic signature assets."
  ],

  fields: [
    // ------------------------------------------------------------
    // Form / student details
    // ------------------------------------------------------------
    { key: "applicationYear", labelSi: "අයදුම් වර්ෂය", labelEn: "Application Year", type: "number", required: true },
    { key: "schoolName", labelSi: "පාසලේ නම", labelEn: "School Name", type: "text", required: true },
    { key: "gradeAppliedFor", labelSi: "ඇතුළත් වීමට ඉල්ලුම් කරන ශ්‍රේණිය", labelEn: "Grade Applied For", type: "number", required: true },
    { key: "admissionCategory", labelSi: "අයදුම් කරන කාණ්ඩය", labelEn: "Admission Category", type: "text", required: true },

    { key: "studentFullName", labelSi: "ශිෂ්‍යයාගේ / ශිෂ්‍යාවගේ සම්පූර්ණ නම", labelEn: "Student Full Name", type: "text", required: true },
    { key: "studentNameWithInitialsSinhalaTamil", labelSi: "මුලකුරු සමග නම - සිංහල/දෙමළ", labelEn: "Name with Initials - Sinhala/Tamil", type: "text", required: true },
    { key: "studentNameWithInitialsEnglish", labelSi: "මුලකුරු සමග නම - ඉංග්‍රීසි", labelEn: "Name with Initials - English", type: "text", required: true },
    { key: "studentGender", labelSi: "ස්ත්‍රී / පුරුෂ භාවය", labelEn: "Gender", type: "text", required: true },
    { key: "studentReligion", labelSi: "ආගම", labelEn: "Religion", type: "text", required: true },
    { key: "mediumOfStudy", labelSi: "ඉගෙනුම් මාධ්‍යය", labelEn: "Medium of Study", type: "text", required: true },
    { key: "birthYear", labelSi: "උපන් වර්ෂය", labelEn: "Birth Year", type: "number", required: true },
    { key: "birthMonth", labelSi: "උපන් මාසය", labelEn: "Birth Month", type: "number", required: true },
    { key: "birthDay", labelSi: "උපන් දිනය", labelEn: "Birth Day", type: "number", required: true },
    { key: "ageYearsAtJan31", labelSi: "ජනවාරි 31 දිනට වයස - අවුරුදු", labelEn: "Age at January 31 - Years", type: "number", required: true },
    { key: "ageMonthsAtJan31", labelSi: "ජනවාරි 31 දිනට වයස - මාස", labelEn: "Age at January 31 - Months", type: "number", required: true },
    { key: "ageDaysAtJan31", labelSi: "ජනවාරි 31 දිනට වයස - දින", labelEn: "Age at January 31 - Days", type: "number", required: true },
    { key: "currentSchoolAndGrade", labelSi: "දැනට ඉගෙනුම ලබන පාසල හා ශ්‍රේණිය", labelEn: "Current School and Grade", type: "text", required: true },

    // ------------------------------------------------------------
    // Applicant / guardian
    // ------------------------------------------------------------
    { key: "applicantFullName", labelSi: "අයදුම්කරුගේ සම්පූර්ණ නම", labelEn: "Applicant Full Name", type: "text", required: true },
    { key: "applicantNameWithInitials", labelSi: "අයදුම්කරුගේ මුලකුරු සමග නම", labelEn: "Applicant Name with Initials", type: "text", required: true },
    { key: "applicantNicNumber", labelSi: "අයදුම්කරුගේ ජාතික හැඳුනුම්පත් අංකය", labelEn: "Applicant NIC Number", type: "nic", required: true },
    { key: "applicantSriLankanCitizen", labelSi: "ශ්‍රී ලාංකිකයෙක් ද", labelEn: "Sri Lankan Citizen", type: "text", required: true },
    { key: "applicantReligion", labelSi: "අයදුම්කරුගේ ආගම", labelEn: "Applicant Religion", type: "text", required: true },
    { key: "applicantPermanentAddress", labelSi: "අයදුම්කරුගේ ස්ථිර ලිපිනය", labelEn: "Applicant Permanent Address", type: "address", required: true },
    { key: "applicantPhoneNumber", labelSi: "අයදුම්කරුගේ දුරකථන අංකය", labelEn: "Applicant Phone Number", type: "phone", required: true },
    { key: "applicantDistrict", labelSi: "දැනට පදිංචි දිස්ත්‍රික්කය", labelEn: "Current District", type: "text", required: true },
    { key: "applicantDivisionalSecretariat", labelSi: "ප්‍රාදේශීය ලේකම් කොට්ඨාසය", labelEn: "Divisional Secretariat", type: "text", required: true },
    { key: "applicantGnDivision", labelSi: "ග්‍රාම නිලධාරි වසම", labelEn: "GN Division", type: "text", required: true },
    { key: "applicantGnDivisionNumber", labelSi: "ග්‍රාම නිලධාරි වසම් අංකය", labelEn: "GN Division Number", type: "text", required: true },
    { key: "currentResidenceAddress", labelSi: "දැනට පදිංචි වී සිටින ස්ථානයේ ලිපිනය", labelEn: "Current Residence Address", type: "address", required: true },
    { key: "previousResidenceAddress", labelSi: "පෙර පදිංචි වී සිටි ස්ථානයේ ලිපිනය", labelEn: "Previous Residence Address", type: "address", required: false },

    // ------------------------------------------------------------
    // Preferred schools
    // ------------------------------------------------------------
    {
      key: "preferredSchool1Name",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 1 - නම",
      labelEn: "Preferred School 1 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool1Type",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 1 - වර්ගය",
      labelEn: "Preferred School 1 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool2Name",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 2 - නම",
      labelEn: "Preferred School 2 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool2Type",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 2 - වර්ගය",
      labelEn: "Preferred School 2 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool3Name",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 3 - නම",
      labelEn: "Preferred School 3 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool3Type",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 3 - වර්ගය",
      labelEn: "Preferred School 3 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool4Name",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 4 - නම",
      labelEn: "Preferred School 4 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool4Type",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 4 - වර්ගය",
      labelEn: "Preferred School 4 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool5Name",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 5 - නම",
      labelEn: "Preferred School 5 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool5Type",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 5 - වර්ගය",
      labelEn: "Preferred School 5 - Type",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool6Name",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 6 - නම",
      labelEn: "Preferred School 6 - Name",
      type: "text",
      required: false,
    },
    {
      key: "preferredSchool6Type",
      labelSi: "ඉල්ලුම් කරන වෙනත් පාසල 6 - වර්ගය",
      labelEn: "Preferred School 6 - Type",
      type: "text",
      required: false,
    },

    // ------------------------------------------------------------
    // 4.1 - transfer category
    // ------------------------------------------------------------
    { key: "criteria411NewWorkplaceStartDate", labelSi: "4.1.1 නව සේවා ස්ථානයේ වැඩ භාරගත් දිනය", labelEn: "4.1.1 New Workplace Start Date", type: "date", required: false },
    { key: "criteria412NewWorkplaceNameAddress", labelSi: "4.1.2 නව සේවා ස්ථානයේ නම හා ලිපිනය", labelEn: "4.1.2 New Workplace Name and Address", type: "text", required: false },
    { key: "criteria413PreviousWorkplaceNameAddress", labelSi: "4.1.3 පෙර සේවා ස්ථානයේ නම හා ලිපිනය", labelEn: "4.1.3 Previous Workplace Name and Address", type: "text", required: false },
    { key: "criteria414PreviousWorkplaceServicePeriod", labelSi: "4.1.4 පෙර සේවා ස්ථානයේ සේවා කාලය", labelEn: "4.1.4 Previous Workplace Service Period", type: "text", required: false },
    { key: "criteria415ElapsedYears", labelSi: "4.1.5 ගත වූ කාලය - අවුරුදු", labelEn: "4.1.5 Elapsed Years", type: "number", required: false },
    { key: "criteria415ElapsedMonths", labelSi: "4.1.5 ගත වූ කාලය - මාස", labelEn: "4.1.5 Elapsed Months", type: "number", required: false },
    { key: "criteria415ElapsedDays", labelSi: "4.1.5 ගත වූ කාලය - දින", labelEn: "4.1.5 Elapsed Days", type: "number", required: false },
    { key: "criteria416PreviousToNewWorkplaceDistanceKm", labelSi: "4.1.6 පෙර සේවා ස්ථානයේ සිට නව සේවා ස්ථානයට දුර", labelEn: "4.1.6 Previous-to-New Workplace Distance", type: "number", required: false },
    { key: "criteria417ResidenceToSchoolDistanceKm", labelSi: "4.1.7 පදිංචි ස්ථානයේ සිට පාසලට දුර", labelEn: "4.1.7 Residence-to-School Distance", type: "number", required: false },
    { key: "criteria418WorkplaceToSchoolDistanceKm", labelSi: "4.1.8 සේවා ස්ථානයේ සිට පාසලට දුර", labelEn: "4.1.8 Workplace-to-School Distance", type: "number", required: false },
    { key: "criteria419TransferReason", labelSi: "4.1.9 ස්ථාන මාරුවීමට හේතුව", labelEn: "4.1.9 Transfer Reason", type: "text", required: false },

    // ------------------------------------------------------------
    // 4.2 - returned from abroad
    // ------------------------------------------------------------
    { key: "criteria421ReturnDateToSriLanka", labelSi: "4.2.1 ශ්‍රී ලංකාවට නැවත පැමිණි දිනය", labelEn: "4.2.1 Return Date to Sri Lanka", type: "date", required: false },
    { key: "criteria422ForeignStayFromDate", labelSi: "4.2.2 විදේශගතව සිටි කාලය - ආරම්භය", labelEn: "4.2.2 Foreign Stay From Date", type: "date", required: false },
    { key: "criteria422ForeignStayToDate", labelSi: "4.2.2 විදේශගතව සිටි කාලය - අවසානය", labelEn: "4.2.2 Foreign Stay To Date", type: "date", required: false },
    { key: "criteria423ReasonForForeignResidence", labelSi: "4.2.3 විදේශගත වූ හේතුව", labelEn: "4.2.3 Reason for Foreign Residence", type: "text", required: false },
    { key: "criteria424ResidenceToSchoolDistanceKm", labelSi: "4.2.4 පදිංචි ස්ථානයේ සිට පාසලට දුර", labelEn: "4.2.4 Residence-to-School Distance", type: "number", required: false },

    // ------------------------------------------------------------
    // 4.3 - residence change
    // ------------------------------------------------------------
    { key: "criteria431ReasonForResidenceChange", labelSi: "4.3.1 පදිංචිය වෙනස් කිරීමට හේතුව", labelEn: "4.3.1 Reason for Residence Change", type: "text", required: false },
    { key: "criteria432NewResidenceArrivalDate", labelSi: "4.3.2 නව පදිංචි ස්ථානයට පැමිණි දිනය", labelEn: "4.3.2 New Residence Arrival Date", type: "date", required: false },
    { key: "criteria433PreviousResidenceAddress", labelSi: "4.3.3 පෙර පදිංචි ස්ථානයේ ලිපිනය", labelEn: "4.3.3 Previous Residence Address", type: "address", required: false },
    { key: "criteria434NewResidenceAddress", labelSi: "4.3.4 නව පදිංචි ස්ථානයේ ලිපිනය", labelEn: "4.3.4 New Residence Address", type: "address", required: false },
    { key: "criteria435NewResidenceToSchoolDistanceKm", labelSi: "4.3.5 නව පදිංචි ස්ථානයේ සිට පාසලට දුර", labelEn: "4.3.5 New Residence-to-School Distance", type: "number", required: false },
    { key: "criteria436NewToPreviousResidenceDistanceKm", labelSi: "4.3.6 නව හා පෙර පදිංචි ස්ථාන අතර දුර", labelEn: "4.3.6 New-to-Previous Residence Distance", type: "number", required: false },

    // ------------------------------------------------------------
    // 4.4 - second transfer category
    // ------------------------------------------------------------
    { key: "criteria441NewWorkplaceStartDate", labelSi: "4.4.1 නව සේවා ස්ථානයේ වැඩ භාරගත් දිනය", labelEn: "4.4.1 New Workplace Start Date", type: "date", required: false },
    { key: "criteria442NewWorkplaceNameAddress", labelSi: "4.4.2 නව සේවා ස්ථානයේ නම හා ලිපිනය", labelEn: "4.4.2 New Workplace Name and Address", type: "text", required: false },
    { key: "criteria443PreviousWorkplaceNameAddress", labelSi: "4.4.3 පෙර සේවා ස්ථානයේ නම හා ලිපිනය", labelEn: "4.4.3 Previous Workplace Name and Address", type: "text", required: false },
    { key: "criteria444PreviousWorkplaceServicePeriod", labelSi: "4.4.4 පෙර සේවා ස්ථානයේ සේවා කාලය", labelEn: "4.4.4 Previous Workplace Service Period", type: "text", required: false },
    { key: "criteria445ElapsedYears", labelSi: "4.4.5 ගත වූ කාලය - අවුරුදු", labelEn: "4.4.5 Elapsed Years", type: "number", required: false },
    { key: "criteria445ElapsedMonths", labelSi: "4.4.5 ගත වූ කාලය - මාස", labelEn: "4.4.5 Elapsed Months", type: "number", required: false },
    { key: "criteria445ElapsedDays", labelSi: "4.4.5 ගත වූ කාලය - දින", labelEn: "4.4.5 Elapsed Days", type: "number", required: false },
    { key: "criteria446PreviousToNewWorkplaceDistanceKm", labelSi: "4.4.6 පෙර සිට නව සේවා ස්ථානයට දුර", labelEn: "4.4.6 Previous-to-New Workplace Distance", type: "number", required: false },
    { key: "criteria447ResidenceToSchoolDistanceKm", labelSi: "4.4.7 පදිංචි ස්ථානයේ සිට පාසලට දුර", labelEn: "4.4.7 Residence-to-School Distance", type: "number", required: false },
    { key: "criteria448WorkplaceToSchoolDistanceKm", labelSi: "4.4.8 සේවා ස්ථානයේ සිට පාසලට දුර", labelEn: "4.4.8 Workplace-to-School Distance", type: "number", required: false },
    { key: "criteria449TransferReason", labelSi: "4.4.9 ස්ථාන මාරුවීමට හේතුව", labelEn: "4.4.9 Transfer Reason", type: "text", required: false },

    // ------------------------------------------------------------
    // 4.5 - scholarship category
    // ------------------------------------------------------------
    { key: "criteria451ScholarshipExamYear", labelSi: "4.5.1 ශිෂ්‍යත්ව විභාග වර්ෂය", labelEn: "4.5.1 Scholarship Examination Year", type: "number", required: false },
    { key: "criteria452ScholarshipExamDistrict", labelSi: "4.5.2 ශිෂ්‍යත්ව විභාග පාසලේ දිස්ත්‍රික්කය", labelEn: "4.5.2 Scholarship Examination District", type: "text", required: false },
    { key: "criteria453ScholarshipMarks", labelSi: "4.5.3 ශිෂ්‍යත්ව ලකුණු", labelEn: "4.5.3 Scholarship Marks", type: "number", required: false },
    { key: "criteria454ResidenceToSchoolDistanceKm", labelSi: "4.5.4 පදිංචි ස්ථානයේ සිට පාසලට දුර", labelEn: "4.5.4 Residence-to-School Distance", type: "number", required: false },

    // ------------------------------------------------------------
    // 4.6 - staff category
    // ------------------------------------------------------------
    { key: "criteria461OccupationDesignation", labelSi: "4.6.1 රැකියාව / තනතුර", labelEn: "4.6.1 Occupation / Designation", type: "text", required: false },
    { key: "criteria462CurrentWorkplaceNameAddress", labelSi: "4.6.2 වර්තමාන සේවා ස්ථානයේ නම හා ලිපිනය", labelEn: "4.6.2 Current Workplace Name and Address", type: "text", required: false },
    { key: "criteria463CurrentWorkplaceServicePeriod", labelSi: "4.6.3 වර්තමාන සේවා ස්ථානයේ සේවා කාලය", labelEn: "4.6.3 Current Workplace Service Period", type: "text", required: false },
    { key: "criteria464PermanentPublicServicePeriod", labelSi: "4.6.4 රාජ්‍ය සේවයේ ස්ථිර සේවා කාලය", labelEn: "4.6.4 Permanent Public Service Period", type: "text", required: false },
    { key: "criteria465ResidenceToSchoolDistanceKm", labelSi: "4.6.5 පදිංචි ස්ථානයේ සිට පාසලට දුර", labelEn: "4.6.5 Residence-to-School Distance", type: "number", required: false },
    { key: "criteria466WorkplaceToSchoolDistanceKm", labelSi: "4.6.6 සේවා ස්ථානයේ සිට පාසලට දුර", labelEn: "4.6.6 Workplace-to-School Distance", type: "number", required: false },

    // ------------------------------------------------------------
    // 4.7 academic progress
    // ------------------------------------------------------------
    { key: "criteria47FinalTermTotalMarks", labelSi: "අවසාන වාර පරීක්ෂණයේ මුළු ලකුණු", labelEn: "Final Term Total Marks", type: "number", required: false },
    { key: "criteria47FinalTermAverageMarks", labelSi: "අවසාන වාර පරීක්ෂණයේ ලකුණු සාමාන්‍යය", labelEn: "Final Term Average Marks", type: "number", required: false },

    // ------------------------------------------------------------
    // 4.8 achievements
    // ------------------------------------------------------------
    {
      key: "sport1Event",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 1 - තරගය/ඉසව්ව",
      labelEn: "Sports Achievement 1 - Event",
      type: "text",
      required: false,
    },
    {
      key: "sport1ParticipationType",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 1 - තනි/සමූහ",
      labelEn: "Sports Achievement 1 - Individual/Team",
      type: "text",
      required: false,
    },
    {
      key: "sport1Year",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 1 - වර්ෂය",
      labelEn: "Sports Achievement 1 - Year",
      type: "number",
      required: false,
    },
    {
      key: "sport1Category",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 1 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Sports Achievement 1 - Category",
      type: "text",
      required: false,
    },
    {
      key: "sport1AchievementLevel",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 1 - මට්ටම",
      labelEn: "Sports Achievement 1 - Level",
      type: "text",
      required: false,
    },
    {
      key: "sport1PlaceOrParticipation",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 1 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Sports Achievement 1 - Place/Participation",
      type: "text",
      required: false,
    },
    {
      key: "sport2Event",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 2 - තරගය/ඉසව්ව",
      labelEn: "Sports Achievement 2 - Event",
      type: "text",
      required: false,
    },
    {
      key: "sport2ParticipationType",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 2 - තනි/සමූහ",
      labelEn: "Sports Achievement 2 - Individual/Team",
      type: "text",
      required: false,
    },
    {
      key: "sport2Year",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 2 - වර්ෂය",
      labelEn: "Sports Achievement 2 - Year",
      type: "number",
      required: false,
    },
    {
      key: "sport2Category",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 2 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Sports Achievement 2 - Category",
      type: "text",
      required: false,
    },
    {
      key: "sport2AchievementLevel",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 2 - මට්ටම",
      labelEn: "Sports Achievement 2 - Level",
      type: "text",
      required: false,
    },
    {
      key: "sport2PlaceOrParticipation",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 2 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Sports Achievement 2 - Place/Participation",
      type: "text",
      required: false,
    },
    {
      key: "sport3Event",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 3 - තරගය/ඉසව්ව",
      labelEn: "Sports Achievement 3 - Event",
      type: "text",
      required: false,
    },
    {
      key: "sport3ParticipationType",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 3 - තනි/සමූහ",
      labelEn: "Sports Achievement 3 - Individual/Team",
      type: "text",
      required: false,
    },
    {
      key: "sport3Year",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 3 - වර්ෂය",
      labelEn: "Sports Achievement 3 - Year",
      type: "number",
      required: false,
    },
    {
      key: "sport3Category",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 3 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Sports Achievement 3 - Category",
      type: "text",
      required: false,
    },
    {
      key: "sport3AchievementLevel",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 3 - මට්ටම",
      labelEn: "Sports Achievement 3 - Level",
      type: "text",
      required: false,
    },
    {
      key: "sport3PlaceOrParticipation",
      labelSi: "ක්‍රීඩා ජයග්‍රහණය 3 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Sports Achievement 3 - Place/Participation",
      type: "text",
      required: false,
    },

    {
      key: "aesthetic1Event",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 1 - තරගය/ඉසව්ව",
      labelEn: "Aesthetic Achievement 1 - Event",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic1ParticipationType",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 1 - තනි/සමූහ",
      labelEn: "Aesthetic Achievement 1 - Individual/Team",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic1Year",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 1 - වර්ෂය",
      labelEn: "Aesthetic Achievement 1 - Year",
      type: "number",
      required: false,
    },
    {
      key: "aesthetic1Category",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 1 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Aesthetic Achievement 1 - Category",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic1AchievementLevel",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 1 - මට්ටම",
      labelEn: "Aesthetic Achievement 1 - Level",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic1PlaceOrParticipation",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 1 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Aesthetic Achievement 1 - Place/Participation",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic2Event",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 2 - තරගය/ඉසව්ව",
      labelEn: "Aesthetic Achievement 2 - Event",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic2ParticipationType",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 2 - තනි/සමූහ",
      labelEn: "Aesthetic Achievement 2 - Individual/Team",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic2Year",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 2 - වර්ෂය",
      labelEn: "Aesthetic Achievement 2 - Year",
      type: "number",
      required: false,
    },
    {
      key: "aesthetic2Category",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 2 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Aesthetic Achievement 2 - Category",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic2AchievementLevel",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 2 - මට්ටම",
      labelEn: "Aesthetic Achievement 2 - Level",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic2PlaceOrParticipation",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 2 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Aesthetic Achievement 2 - Place/Participation",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic3Event",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 3 - තරගය/ඉසව්ව",
      labelEn: "Aesthetic Achievement 3 - Event",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic3ParticipationType",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 3 - තනි/සමූහ",
      labelEn: "Aesthetic Achievement 3 - Individual/Team",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic3Year",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 3 - වර්ෂය",
      labelEn: "Aesthetic Achievement 3 - Year",
      type: "number",
      required: false,
    },
    {
      key: "aesthetic3Category",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 3 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Aesthetic Achievement 3 - Category",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic3AchievementLevel",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 3 - මට්ටම",
      labelEn: "Aesthetic Achievement 3 - Level",
      type: "text",
      required: false,
    },
    {
      key: "aesthetic3PlaceOrParticipation",
      labelSi: "සෞන්දර්ය ජයග්‍රහණය 3 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Aesthetic Achievement 3 - Place/Participation",
      type: "text",
      required: false,
    },

    {
      key: "innovation1Name",
      labelSi: "නව නිපැයුම 1",
      labelEn: "Innovation 1",
      type: "text",
      required: false,
    },
    {
      key: "innovation1Year",
      labelSi: "නව නිපැයුම 1 - වර්ෂය",
      labelEn: "Innovation 1 - Year",
      type: "number",
      required: false,
    },
    {
      key: "innovation1Category",
      labelSi: "නව නිපැයුම 1 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Innovation 1 - Category",
      type: "text",
      required: false,
    },
    {
      key: "innovation1AchievementLevel",
      labelSi: "නව නිපැයුම 1 - ජයග්‍රහණ මට්ටම",
      labelEn: "Innovation 1 - Achievement Level",
      type: "text",
      required: false,
    },
    {
      key: "innovation1PlaceOrParticipation",
      labelSi: "නව නිපැයුම 1 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Innovation 1 - Place/Participation",
      type: "text",
      required: false,
    },
    {
      key: "innovation2Name",
      labelSi: "නව නිපැයුම 2",
      labelEn: "Innovation 2",
      type: "text",
      required: false,
    },
    {
      key: "innovation2Year",
      labelSi: "නව නිපැයුම 2 - වර්ෂය",
      labelEn: "Innovation 2 - Year",
      type: "number",
      required: false,
    },
    {
      key: "innovation2Category",
      labelSi: "නව නිපැයුම 2 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Innovation 2 - Category",
      type: "text",
      required: false,
    },
    {
      key: "innovation2AchievementLevel",
      labelSi: "නව නිපැයුම 2 - ජයග්‍රහණ මට්ටම",
      labelEn: "Innovation 2 - Achievement Level",
      type: "text",
      required: false,
    },
    {
      key: "innovation2PlaceOrParticipation",
      labelSi: "නව නිපැයුම 2 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Innovation 2 - Place/Participation",
      type: "text",
      required: false,
    },
    {
      key: "innovation3Name",
      labelSi: "නව නිපැයුම 3",
      labelEn: "Innovation 3",
      type: "text",
      required: false,
    },
    {
      key: "innovation3Year",
      labelSi: "නව නිපැයුම 3 - වර්ෂය",
      labelEn: "Innovation 3 - Year",
      type: "number",
      required: false,
    },
    {
      key: "innovation3Category",
      labelSi: "නව නිපැයුම 3 - අදාළ අවස්ථාව/කාණ්ඩය",
      labelEn: "Innovation 3 - Category",
      type: "text",
      required: false,
    },
    {
      key: "innovation3AchievementLevel",
      labelSi: "නව නිපැයුම 3 - ජයග්‍රහණ මට්ටම",
      labelEn: "Innovation 3 - Achievement Level",
      type: "text",
      required: false,
    },
    {
      key: "innovation3PlaceOrParticipation",
      labelSi: "නව නිපැයුම 3 - ස්ථානය/සහභාගීත්වය",
      labelEn: "Innovation 3 - Place/Participation",
      type: "text",
      required: false,
    },

    {
      key: "activity1Name",
      labelSi: "විෂය සමගාමී/විෂය බාහිර ක්‍රියාකාරකම 1",
      labelEn: "Co/Extra-curricular Activity 1",
      type: "text",
      required: false,
    },
    {
      key: "activity1Year",
      labelSi: "ක්‍රියාකාරකම 1 - වර්ෂය",
      labelEn: "Activity 1 - Year",
      type: "number",
      required: false,
    },
    {
      key: "activity1AchievementLevel",
      labelSi: "ක්‍රියාකාරකම 1 - ජයග්‍රහණ මට්ටම",
      labelEn: "Activity 1 - Achievement Level",
      type: "text",
      required: false,
    },
    {
      key: "activity2Name",
      labelSi: "විෂය සමගාමී/විෂය බාහිර ක්‍රියාකාරකම 2",
      labelEn: "Co/Extra-curricular Activity 2",
      type: "text",
      required: false,
    },
    {
      key: "activity2Year",
      labelSi: "ක්‍රියාකාරකම 2 - වර්ෂය",
      labelEn: "Activity 2 - Year",
      type: "number",
      required: false,
    },
    {
      key: "activity2AchievementLevel",
      labelSi: "ක්‍රියාකාරකම 2 - ජයග්‍රහණ මට්ටම",
      labelEn: "Activity 2 - Achievement Level",
      type: "text",
      required: false,
    },
    {
      key: "activity3Name",
      labelSi: "විෂය සමගාමී/විෂය බාහිර ක්‍රියාකාරකම 3",
      labelEn: "Co/Extra-curricular Activity 3",
      type: "text",
      required: false,
    },
    {
      key: "activity3Year",
      labelSi: "ක්‍රියාකාරකම 3 - වර්ෂය",
      labelEn: "Activity 3 - Year",
      type: "number",
      required: false,
    },
    {
      key: "activity3AchievementLevel",
      labelSi: "ක්‍රියාකාරකම 3 - ජයග්‍රහණ මට්ටම",
      labelEn: "Activity 3 - Achievement Level",
      type: "text",
      required: false,
    },

    {
      key: "leadership1OrganizationOrActivity",
      labelSi: "නායකත්ව තනතුර 1 - සමිතිය/සංගමය/ක්‍රියාකාරකම",
      labelEn: "Leadership 1 - Organization/Activity",
      type: "text",
      required: false,
    },
    {
      key: "leadership1Position",
      labelSi: "නායකත්ව තනතුර 1 - තනතුර",
      labelEn: "Leadership 1 - Position",
      type: "text",
      required: false,
    },
    {
      key: "leadership1Year",
      labelSi: "නායකත්ව තනතුර 1 - වර්ෂය",
      labelEn: "Leadership 1 - Year",
      type: "number",
      required: false,
    },
    {
      key: "leadership2OrganizationOrActivity",
      labelSi: "නායකත්ව තනතුර 2 - සමිතිය/සංගමය/ක්‍රියාකාරකම",
      labelEn: "Leadership 2 - Organization/Activity",
      type: "text",
      required: false,
    },
    {
      key: "leadership2Position",
      labelSi: "නායකත්ව තනතුර 2 - තනතුර",
      labelEn: "Leadership 2 - Position",
      type: "text",
      required: false,
    },
    {
      key: "leadership2Year",
      labelSi: "නායකත්ව තනතුර 2 - වර්ෂය",
      labelEn: "Leadership 2 - Year",
      type: "number",
      required: false,
    },
    {
      key: "leadership3OrganizationOrActivity",
      labelSi: "නායකත්ව තනතුර 3 - සමිතිය/සංගමය/ක්‍රියාකාරකම",
      labelEn: "Leadership 3 - Organization/Activity",
      type: "text",
      required: false,
    },
    {
      key: "leadership3Position",
      labelSi: "නායකත්ව තනතුර 3 - තනතුර",
      labelEn: "Leadership 3 - Position",
      type: "text",
      required: false,
    },
    {
      key: "leadership3Year",
      labelSi: "නායකත්ව තනතුර 3 - වර්ෂය",
      labelEn: "Leadership 3 - Year",
      type: "number",
      required: false,
    },

    { key: "declarationDate", labelSi: "ප්‍රකාශයේ දිනය", labelEn: "Declaration Date", type: "date", required: true, helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න." },
  ],
};
