import { EDUCATION_CATEGORY } from "../categories";
import type { DataCollectionForm } from "../types";

export const sltbJobApplicationFormDefinition: DataCollectionForm = {
  id: "sltb-job-application",
  nameSi: "ශ්‍රී ලංකා ගමනාගමන මණ්ඩල රැකියා අයදුම්පත",
  nameEn: "Sri Lanka Transport Board Job Application",
  documentPath: "/forms/employment/sltb-job-application.pdf",
  category: EDUCATION_CATEGORY,

  generationGuidance: [
    "Generate values only for the fields defined in this form.",
    "Each generated field value corresponds to a {{fieldKey}} placeholder in the static OCR/layout annotation template.",
    "When applying generated values, replace only matching placeholders. Do not modify fixed OCR text, bounding boxes, labels, reading order, page numbers, tables, printer marks, or scan watermarks.",
    "Generate one internally consistent synthetic applicant for a Sri Lanka Transport Board job application.",
    "positionAppliedFor should be a plausible transport-board job title appropriate to the applicant's qualifications.",
    "applicantFullName and nameWithInitials must refer to the same synthetic Sri Lankan applicant and must not refer to a real public figure.",
    "address, province, district, and nearestSltbBusDepot must be geographically plausible and mutually consistent.",
    "birthYear, birthMonth, and birthDay must form a valid date of birth.",
    "ageYearsAsAt20230930, ageMonthsAsAt20230930, and ageDaysAsAt20230930 must exactly match the applicant's date of birth as at 2023-09-30.",
    "nicNumber must be a plausible synthetic Sri Lankan NIC number consistent with the applicant's date of birth where applicable.",
    "religion and nationality must be plausible. isSriLankanCitizen must be a concise yes/no value.",
    "If isSriLankanCitizen is affirmative, citizenshipBasis should state whether citizenship is by descent or registration. If not applicable, return an empty string.",
    "preferredRegionalChoice1 through preferredRegionalChoice3 should be populated in priority order with plausible SLTB regional/work-location preferences.",
    "olExamYear and olExamIndexNumber must be plausible and chronologically consistent with the applicant's age.",
    "Populate O/L subject rows consecutively. Each populated olSubjectNName must have a corresponding olSubjectNResult. Return empty strings for unused rows.",
    "alExamYear and alExamIndexNumber must be plausible and chronologically consistent with the applicant's age.",
    "Populate A/L subject rows consecutively. Each populated alSubjectNName must have a corresponding alSubjectNResult. Return empty strings for unused rows.",
    "weightKg, heightFeet, and heightInches must describe one physically plausible adult applicant.",
    "homePhone and mobilePhone must be plausible synthetic Sri Lankan telephone numbers.",
    "drivingLicenceNumber, drivingLicenceClass, and drivingLicenceValidity are optional and must describe one consistent synthetic driving licence when applicable. If the applicant has no driving licence, return empty strings for all three.",
    "conductorLicenceNumber and conductorLicenceIssuingAuthority are optional and must be mutually consistent when applicable. If the applicant has no conductor licence, return empty strings for both.",
    "previouslyWorkedAtSltb must be a concise yes/no value.",
    "If previouslyWorkedAtSltb is affirmative, previousSltbEmploymentDetails must contain concise plausible former-employment details. Otherwise return an empty string.",
    "previouslyConvictedByCourt must be a concise yes/no value.",
    "If previouslyConvictedByCourt is affirmative, courtConvictionDetails must contain concise synthetic details suitable for the form. Otherwise return an empty string.",
    "declarationDate must use YYYY-MM-DD and must be chronologically plausible.",
    "Keep all generated values concise enough to fit naturally inside their assigned dotted lines or boxes.",
    "Use only synthetic names, identifiers, contact details, education records, licence numbers, and employment information. Do not knowingly generate real personal identifiers.",
    "Return values using exactly the field keys defined in the fields array. Do not invent additional ordinary text fields.",
    "Do not return OCR text, bounding boxes, labels, reading order, page numbers, signatures, printer marks, or scan watermarks. Those are already represented in the static annotation template.",
    "applicantSignature is represented separately as a Signature annotation region and should not be returned as an ordinary text value unless the rendering pipeline explicitly supports synthetic signature-image assets."
  ],

  fields: [
    {
      key: "positionAppliedFor",
      labelSi: "අයදුම් කරන තනතුර",
      labelEn: "Position Applied For",
      type: "text",
      required: true,
    },
    {
      key: "applicantFullName",
      labelSi: "අයදුම්කරුගේ සම්පූර්ණ නම",
      labelEn: "Applicant Full Name",
      type: "text",
      required: true,
    },
    {
      key: "nameWithInitials",
      labelSi: "මුලකුරු සමග නම",
      labelEn: "Name with Initials",
      type: "text",
      required: true,
    },
    {
      key: "address",
      labelSi: "ලිපිනය",
      labelEn: "Address",
      type: "address",
      required: true,
    },

    {
      key: "birthYear",
      labelSi: "උපන් වර්ෂය",
      labelEn: "Birth Year",
      type: "number",
      required: true,
    },
    {
      key: "birthMonth",
      labelSi: "උපන් මාසය",
      labelEn: "Birth Month",
      type: "number",
      required: true,
    },
    {
      key: "birthDay",
      labelSi: "උපන් දිනය",
      labelEn: "Birth Day",
      type: "number",
      required: true,
    },
    {
      key: "ageYearsAsAt20230930",
      labelSi: "2023-09-30 දිනට වයස - අවුරුදු",
      labelEn: "Age as at 2023-09-30 - Years",
      type: "number",
      required: true,
    },
    {
      key: "ageMonthsAsAt20230930",
      labelSi: "2023-09-30 දිනට වයස - මාස",
      labelEn: "Age as at 2023-09-30 - Months",
      type: "number",
      required: true,
    },
    {
      key: "ageDaysAsAt20230930",
      labelSi: "2023-09-30 දිනට වයස - දින",
      labelEn: "Age as at 2023-09-30 - Days",
      type: "number",
      required: true,
    },

    {
      key: "nicNumber",
      labelSi: "ජාතික හැඳුනුම්පත් අංකය",
      labelEn: "National Identity Card Number",
      type: "nic",
      required: true,
    },
    {
      key: "religion",
      labelSi: "ආගම",
      labelEn: "Religion",
      type: "text",
      required: true,
    },
    {
      key: "nationality",
      labelSi: "ජාතිය",
      labelEn: "Nationality",
      type: "text",
      required: true,
    },
    {
      key: "isSriLankanCitizen",
      labelSi: "ශ්‍රී ලාංකික පුරවැසියෙක්ද",
      labelEn: "Sri Lankan Citizen",
      type: "text",
      required: true,
    },
    {
      key: "citizenshipBasis",
      labelSi: "පුරවැසිභාවය ලියාපදිංචියෙන්ද පරම්පරාවෙන්ද",
      labelEn: "Citizenship by Registration or Descent",
      type: "text",
      required: false,
    },

    {
      key: "province",
      labelSi: "පළාත",
      labelEn: "Province",
      type: "text",
      required: true,
    },
    {
      key: "district",
      labelSi: "දිස්ත්‍රික්කය",
      labelEn: "District",
      type: "text",
      required: true,
    },
    {
      key: "nearestSltbBusDepot",
      labelSi: "ආසන්නතම ශ්‍රී ලංගම බස් ඩිපෝව",
      labelEn: "Nearest SLTB Bus Depot",
      type: "text",
      required: true,
    },

    {
      key: "preferredRegionalChoice1",
      labelSi: "අයදුම් කරන ප්‍රාදේශික ප්‍රමුඛතාව 1",
      labelEn: "Preferred Regional Choice 1",
      type: "text",
      required: true,
    },
    {
      key: "preferredRegionalChoice2",
      labelSi: "අයදුම් කරන ප්‍රාදේශික ප්‍රමුඛතාව 2",
      labelEn: "Preferred Regional Choice 2",
      type: "text",
      required: false,
    },
    {
      key: "preferredRegionalChoice3",
      labelSi: "අයදුම් කරන ප්‍රාදේශික ප්‍රමුඛතාව 3",
      labelEn: "Preferred Regional Choice 3",
      type: "text",
      required: false,
    },

    {
      key: "olExamYear",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ වර්ෂය",
      labelEn: "O/L Examination Year",
      type: "number",
      required: true,
    },
    {
      key: "olExamIndexNumber",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විභාග අංකය",
      labelEn: "O/L Examination Index Number",
      type: "text",
      required: true,
    },

    {
      key: "olSubject1Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 1",
      labelEn: "O/L Subject 1",
      type: "text",
      required: false,
    },
    {
      key: "olSubject1Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 1 සාමාර්ථය",
      labelEn: "O/L Subject 1 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject2Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 2",
      labelEn: "O/L Subject 2",
      type: "text",
      required: false,
    },
    {
      key: "olSubject2Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 2 සාමාර්ථය",
      labelEn: "O/L Subject 2 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject3Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 3",
      labelEn: "O/L Subject 3",
      type: "text",
      required: false,
    },
    {
      key: "olSubject3Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 3 සාමාර්ථය",
      labelEn: "O/L Subject 3 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject4Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 4",
      labelEn: "O/L Subject 4",
      type: "text",
      required: false,
    },
    {
      key: "olSubject4Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 4 සාමාර්ථය",
      labelEn: "O/L Subject 4 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject5Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 5",
      labelEn: "O/L Subject 5",
      type: "text",
      required: false,
    },
    {
      key: "olSubject5Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 5 සාමාර්ථය",
      labelEn: "O/L Subject 5 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject6Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 6",
      labelEn: "O/L Subject 6",
      type: "text",
      required: false,
    },
    {
      key: "olSubject6Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 6 සාමාර්ථය",
      labelEn: "O/L Subject 6 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject7Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 7",
      labelEn: "O/L Subject 7",
      type: "text",
      required: false,
    },
    {
      key: "olSubject7Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 7 සාමාර්ථය",
      labelEn: "O/L Subject 7 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject8Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 8",
      labelEn: "O/L Subject 8",
      type: "text",
      required: false,
    },
    {
      key: "olSubject8Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 8 සාමාර්ථය",
      labelEn: "O/L Subject 8 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject9Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 9",
      labelEn: "O/L Subject 9",
      type: "text",
      required: false,
    },
    {
      key: "olSubject9Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 9 සාමාර්ථය",
      labelEn: "O/L Subject 9 Result",
      type: "text",
      required: false,
    },
    {
      key: "olSubject10Name",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 10",
      labelEn: "O/L Subject 10",
      type: "text",
      required: false,
    },
    {
      key: "olSubject10Result",
      labelSi: "අ.පො.ස. සාමාන්‍ය පෙළ විෂය 10 සාමාර්ථය",
      labelEn: "O/L Subject 10 Result",
      type: "text",
      required: false,
    },

    {
      key: "alExamYear",
      labelSi: "අ.පො.ස. උසස් පෙළ වර්ෂය",
      labelEn: "A/L Examination Year",
      type: "number",
      required: false,
    },
    {
      key: "alExamIndexNumber",
      labelSi: "අ.පො.ස. උසස් පෙළ විභාග අංකය",
      labelEn: "A/L Examination Index Number",
      type: "text",
      required: false,
    },

    {
      key: "alSubject1Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 1",
      labelEn: "A/L Subject 1",
      type: "text",
      required: false,
    },
    {
      key: "alSubject1Result",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 1 සාමාර්ථය",
      labelEn: "A/L Subject 1 Result",
      type: "text",
      required: false,
    },
    {
      key: "alSubject2Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 2",
      labelEn: "A/L Subject 2",
      type: "text",
      required: false,
    },
    {
      key: "alSubject2Result",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 2 සාමාර්ථය",
      labelEn: "A/L Subject 2 Result",
      type: "text",
      required: false,
    },
    {
      key: "alSubject3Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 3",
      labelEn: "A/L Subject 3",
      type: "text",
      required: false,
    },
    {
      key: "alSubject3Result",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 3 සාමාර්ථය",
      labelEn: "A/L Subject 3 Result",
      type: "text",
      required: false,
    },
    {
      key: "alSubject4Name",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 4",
      labelEn: "A/L Subject 4",
      type: "text",
      required: false,
    },
    {
      key: "alSubject4Result",
      labelSi: "අ.පො.ස. උසස් පෙළ විෂය 4 සාමාර්ථය",
      labelEn: "A/L Subject 4 Result",
      type: "text",
      required: false,
    },

    {
      key: "weightKg",
      labelSi: "බර (කිලෝ)",
      labelEn: "Weight (kg)",
      type: "number",
      required: true,
    },
    {
      key: "heightFeet",
      labelSi: "උස - අඩි",
      labelEn: "Height - Feet",
      type: "number",
      required: true,
    },
    {
      key: "heightInches",
      labelSi: "උස - අඟල්",
      labelEn: "Height - Inches",
      type: "number",
      required: true,
    },
    {
      key: "homePhone",
      labelSi: "නිවසේ දුරකථන අංකය",
      labelEn: "Home Phone Number",
      type: "phone",
      required: false,
    },
    {
      key: "mobilePhone",
      labelSi: "ජංගම දුරකථන අංකය",
      labelEn: "Mobile Phone Number",
      type: "phone",
      required: true,
    },

    {
      key: "drivingLicenceNumber",
      labelSi: "රියදුරු බලපත්‍ර අංකය",
      labelEn: "Driving Licence Number",
      type: "text",
      required: false,
    },
    {
      key: "drivingLicenceClass",
      labelSi: "රියදුරු බලපත්‍ර කාණ්ඩය",
      labelEn: "Driving Licence Class",
      type: "text",
      required: false,
    },
    {
      key: "drivingLicenceValidity",
      labelSi: "රියදුරු බලපත්‍ර වලංගු කාලය",
      labelEn: "Driving Licence Validity",
      type: "text",
      required: false,
    },

    {
      key: "conductorLicenceNumber",
      labelSi: "කොන්දොස්තර බලපත්‍ර අංකය",
      labelEn: "Conductor Licence Number",
      type: "text",
      required: false,
    },
    {
      key: "conductorLicenceIssuingAuthority",
      labelSi: "කොන්දොස්තර බලපත්‍රය නිකුත් කළ ආයතනය",
      labelEn: "Conductor Licence Issuing Authority",
      type: "text",
      required: false,
    },

    {
      key: "previouslyWorkedAtSltb",
      labelSi: "මීට ඉහතදී ශ්‍රී ලංකා ගමනාගමන මණ්ඩලයේ සේවය කර ඇත් ද",
      labelEn: "Previously Employed by SLTB",
      type: "text",
      required: true,
    },
    {
      key: "previousSltbEmploymentDetails",
      labelSi: "පෙර ශ්‍රී ලංගම සේවා විස්තර",
      labelEn: "Previous SLTB Employment Details",
      type: "text",
      required: false,
    },
    {
      key: "previouslyConvictedByCourt",
      labelSi: "මීට ඉහතදී උසාවියකින් වරදකරු වී තිබේ ද",
      labelEn: "Previously Convicted by a Court",
      type: "text",
      required: true,
    },
    {
      key: "courtConvictionDetails",
      labelSi: "උසාවි වරදකරු වීම පිළිබඳ විස්තර",
      labelEn: "Court Conviction Details",
      type: "text",
      required: false,
    },
    {
      key: "declarationDate",
      labelSi: "දිනය",
      labelEn: "Declaration Date",
      type: "date",
      required: true,
      helpTextSi: "YYYY-MM-DD ආකෘතිය භාවිතා කරන්න.",
    },
  ],
};
