name: Deploy Admin App Production

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Verify Vercel Access
        run: |
          vercel whoami --token=${{ secrets.VERCEL_TOKEN }}
          vercel project ls \
            --scope=sri-page \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Remove stale Vercel configuration
        run: rm -rf .vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          DEPLOYMENT_URL=$(vercel deploy \
            --prebuilt \
            --prod \
            --token=${{ secrets.VERCEL_TOKEN }})

          echo "DEPLOYMENT SUCCESSFUL!"
          echo "Live URL: $DEPLOYMENT_URL"